<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/customer/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.customer.'), function () {

Route::get('customers', ['as'=> 'customers.index', 'uses' => 'Customer\CustomerController@index']);
Route::post('customers', ['as'=> 'customers.store', 'uses' => 'Customer\CustomerController@store']);
Route::get('customers/create', ['as'=> 'customers.create', 'uses' => 'Customer\CustomerController@create']);
Route::put('customers/{customers}', ['as'=> 'customers.update', 'uses' => 'Customer\CustomerController@update']);
Route::patch('customers/{customers}', ['as'=> 'customers.update', 'uses' => 'Customer\CustomerController@update']);
Route::get('customers/{id}/delete', ['as' => 'customers.delete', 'uses' => 'Customer\CustomerController@getDelete']);
Route::get('customers/{id}/confirm-delete', ['as' => 'customers.confirm-delete', 'uses' => 'Customer\CustomerController@getModalDelete']);
Route::get('customers/{customers}', ['as'=> 'customers.show', 'uses' => 'Customer\CustomerController@show']);
Route::get('customers/{customers}/edit', ['as'=> 'customers.edit', 'uses' => 'Customer\CustomerController@edit']);

});


Route::group(array('prefix' => 'admin/cusromerType/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.cusromerType.'), function () {

Route::get('customertypes', ['as'=> 'customertypes.index', 'uses' => 'Cusromer_Type\CustomertypeController@index']);
Route::post('customertypes', ['as'=> 'customertypes.store', 'uses' => 'Cusromer_Type\CustomertypeController@store']);
Route::get('customertypes/create', ['as'=> 'customertypes.create', 'uses' => 'Cusromer_Type\CustomertypeController@create']);
Route::put('customertypes/{customertypes}', ['as'=> 'customertypes.update', 'uses' => 'Cusromer_Type\CustomertypeController@update']);
Route::patch('customertypes/{customertypes}', ['as'=> 'customertypes.update', 'uses' => 'Cusromer_Type\CustomertypeController@update']);
Route::get('customertypes/{id}/delete', ['as' => 'customertypes.delete', 'uses' => 'Cusromer_Type\CustomertypeController@getDelete']);
Route::get('customertypes/{id}/confirm-delete', ['as' => 'customertypes.confirm-delete', 'uses' => 'Cusromer_Type\CustomertypeController@getModalDelete']);
Route::get('customertypes/{customertypes}', ['as'=> 'customertypes.show', 'uses' => 'Cusromer_Type\CustomertypeController@show']);
Route::get('customertypes/{customertypes}/edit', ['as'=> 'customertypes.edit', 'uses' => 'Cusromer_Type\CustomertypeController@edit']);

});


Route::group(array('prefix' => 'admin/customer/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.customer.'), function () {

Route::get('customers', ['as'=> 'customers.index', 'uses' => 'Customer\CustomerController@index']);
Route::post('customers', ['as'=> 'customers.store', 'uses' => 'Customer\CustomerController@store']);
Route::get('deactivate_customer', ['as'=> 'customers.deactivate_customer', 'uses' => 'Customer\CustomerController@deactivate_customer']);
Route::get('customers/create', ['as'=> 'customers.create', 'uses' => 'Customer\CustomerController@create']);
Route::put('customers/{customers}', ['as'=> 'customers.update', 'uses' => 'Customer\CustomerController@update']);
Route::patch('customers/{customers}', ['as'=> 'customers.update', 'uses' => 'Customer\CustomerController@update']);
Route::get('customers/{id}/delete', ['as' => 'customers.delete', 'uses' => 'Customer\CustomerController@getDelete']);
Route::get('customers/{id}/confirm-delete', ['as' => 'customers.confirm-delete', 'uses' => 'Customer\CustomerController@getModalDelete']);
Route::get('customers/{customers}', ['as'=> 'customers.show', 'uses' => 'Customer\CustomerController@show']);
Route::get('customers/{customers}/edit', ['as'=> 'customers.edit', 'uses' => 'Customer\CustomerController@edit']);

});


Route::group(array('prefix' => 'admin/product/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.product.'), function () {

Route::get('products', ['as'=> 'products.index', 'uses' => 'Product\ProductController@index']);
Route::post('products', ['as'=> 'products.store', 'uses' => 'Product\ProductController@store']);
Route::get('products/create', ['as'=> 'products.create', 'uses' => 'Product\ProductController@create']);
Route::put('products/{products}', ['as'=> 'products.update', 'uses' => 'Product\ProductController@update']);
Route::patch('products/{products}', ['as'=> 'products.update', 'uses' => 'Product\ProductController@update']);
Route::get('products/{id}/delete', ['as' => 'products.delete', 'uses' => 'Product\ProductController@getDelete']);
Route::get('products/{id}/confirm-delete', ['as' => 'products.confirm-delete', 'uses' => 'Product\ProductController@getModalDelete']);
Route::get('products/{products}', ['as'=> 'products.show', 'uses' => 'Product\ProductController@show']);
Route::get('products/{products}/edit', ['as'=> 'products.edit', 'uses' => 'Product\ProductController@edit']);

});


Route::group(array('prefix' => 'admin/productType/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.productType.'), function () {

Route::get('productTypes', ['as'=> 'productTypes.index', 'uses' => 'Product Type\ProductTypeController@index']);
Route::post('productTypes', ['as'=> 'productTypes.store', 'uses' => 'Product Type\ProductTypeController@store']);
Route::get('productTypes/create', ['as'=> 'productTypes.create', 'uses' => 'Product Type\ProductTypeController@create']);
Route::put('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type\ProductTypeController@update']);
Route::patch('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type\ProductTypeController@update']);
Route::get('productTypes/{id}/delete', ['as' => 'productTypes.delete', 'uses' => 'Product Type\ProductTypeController@getDelete']);
Route::get('productTypes/{id}/confirm-delete', ['as' => 'productTypes.confirm-delete', 'uses' => 'Product Type\ProductTypeController@getModalDelete']);
Route::get('productTypes/{productTypes}', ['as'=> 'productTypes.show', 'uses' => 'Product Type\ProductTypeController@show']);
Route::get('productTypes/{productTypes}/edit', ['as'=> 'productTypes.edit', 'uses' => 'Product Type\ProductTypeController@edit']);

});


Route::group(array('prefix' => 'admin/productType/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.productType.'), function () {

Route::get('productTypes', ['as'=> 'productTypes.index', 'uses' => 'Product Type\Product TypeController@index']);
Route::post('productTypes', ['as'=> 'productTypes.store', 'uses' => 'Product Type\Product TypeController@store']);
Route::get('productTypes/create', ['as'=> 'productTypes.create', 'uses' => 'Product Type\Product TypeController@create']);
Route::put('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type\Product TypeController@update']);
Route::patch('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type\Product TypeController@update']);
Route::get('productTypes/{id}/delete', ['as' => 'productTypes.delete', 'uses' => 'Product Type\Product TypeController@getDelete']);
Route::get('productTypes/{id}/confirm-delete', ['as' => 'productTypes.confirm-delete', 'uses' => 'Product Type\Product TypeController@getModalDelete']);
Route::get('productTypes/{productTypes}', ['as'=> 'productTypes.show', 'uses' => 'Product Type\Product TypeController@show']);
Route::get('productTypes/{productTypes}/edit', ['as'=> 'productTypes.edit', 'uses' => 'Product Type\Product TypeController@edit']);

});


Route::group(array('prefix' => 'admin/productType/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.productType.'), function () {

Route::get('productTypes', ['as'=> 'productTypes.index', 'uses' => 'Product Type\Product TypeController@index']);
Route::post('productTypes', ['as'=> 'productTypes.store', 'uses' => 'Product Type\Product TypeController@store']);
Route::get('productTypes/create', ['as'=> 'productTypes.create', 'uses' => 'Product Type\Product TypeController@create']);
Route::put('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type\Product TypeController@update']);
Route::patch('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type\Product TypeController@update']);
Route::get('productTypes/{id}/delete', ['as' => 'productTypes.delete', 'uses' => 'Product Type\Product TypeController@getDelete']);
Route::get('productTypes/{id}/confirm-delete', ['as' => 'productTypes.confirm-delete', 'uses' => 'Product Type\Product TypeController@getModalDelete']);
Route::get('productTypes/{productTypes}', ['as'=> 'productTypes.show', 'uses' => 'Product Type\Product TypeController@show']);
Route::get('productTypes/{productTypes}/edit', ['as'=> 'productTypes.edit', 'uses' => 'Product Type\Product TypeController@edit']);

});


Route::group(array('prefix' => 'admin/productType/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.productType.'), function () {

Route::get('productTypes', ['as'=> 'productTypes.index', 'uses' => 'Product Type\Product TypeController@index']);
Route::post('productTypes', ['as'=> 'productTypes.store', 'uses' => 'Product Type\Product TypeController@store']);
Route::get('productTypes/create', ['as'=> 'productTypes.create', 'uses' => 'Product Type\Product TypeController@create']);
Route::put('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type\Product TypeController@update']);
Route::patch('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type\Product TypeController@update']);
Route::get('productTypes/{id}/delete', ['as' => 'productTypes.delete', 'uses' => 'Product Type\Product TypeController@getDelete']);
Route::get('productTypes/{id}/confirm-delete', ['as' => 'productTypes.confirm-delete', 'uses' => 'Product Type\Product TypeController@getModalDelete']);
Route::get('productTypes/{productTypes}', ['as'=> 'productTypes.show', 'uses' => 'Product Type\Product TypeController@show']);
Route::get('productTypes/{productTypes}/edit', ['as'=> 'productTypes.edit', 'uses' => 'Product Type\Product TypeController@edit']);

});


Route::group(array('prefix' => 'admin/productTypeName/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.productTypeName.'), function () {

Route::get('productTypes', ['as'=> 'productTypes.index', 'uses' => 'Product Type Name\Product TypesController@index']);
Route::post('productTypes', ['as'=> 'productTypes.store', 'uses' => 'Product Type Name\Product TypesController@store']);
Route::get('productTypes/create', ['as'=> 'productTypes.create', 'uses' => 'Product Type Name\Product TypesController@create']);
Route::put('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type Name\Product TypesController@update']);
Route::patch('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type Name\Product TypesController@update']);
Route::get('productTypes/{id}/delete', ['as' => 'productTypes.delete', 'uses' => 'Product Type Name\Product TypesController@getDelete']);
Route::get('productTypes/{id}/confirm-delete', ['as' => 'productTypes.confirm-delete', 'uses' => 'Product Type Name\Product TypesController@getModalDelete']);
Route::get('productTypes/{productTypes}', ['as'=> 'productTypes.show', 'uses' => 'Product Type Name\Product TypesController@show']);
Route::get('productTypes/{productTypes}/edit', ['as'=> 'productTypes.edit', 'uses' => 'Product Type Name\Product TypesController@edit']);

});


Route::group(array('prefix' => 'admin/productTypeName/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.productTypeName.'), function () {

Route::get('productTypes', ['as'=> 'productTypes.index', 'uses' => 'Product Type Name\Product TypesController@index']);
Route::post('productTypes', ['as'=> 'productTypes.store', 'uses' => 'Product Type Name\Product TypesController@store']);
Route::get('productTypes/create', ['as'=> 'productTypes.create', 'uses' => 'Product Type Name\Product TypesController@create']);
Route::put('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type Name\Product TypesController@update']);
Route::patch('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type Name\Product TypesController@update']);
Route::get('productTypes/{id}/delete', ['as' => 'productTypes.delete', 'uses' => 'Product Type Name\Product TypesController@getDelete']);
Route::get('productTypes/{id}/confirm-delete', ['as' => 'productTypes.confirm-delete', 'uses' => 'Product Type Name\Product TypesController@getModalDelete']);
Route::get('productTypes/{productTypes}', ['as'=> 'productTypes.show', 'uses' => 'Product Type Name\Product TypesController@show']);
Route::get('productTypes/{productTypes}/edit', ['as'=> 'productTypes.edit', 'uses' => 'Product Type Name\Product TypesController@edit']);

});


// Route::group(array('prefix' => 'admin/serviceOrder/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.serviceOrder.'), function () {

// Route::get('serviceOrders', ['as'=> 'serviceOrders.index', 'uses' => 'Service Order\Service OrderController@index']);
// Route::get('deactivate_service', ['as'=> 'serviceOrders.deactivate_service', 'uses' => 'Service Order\Service OrderController@deactivate_service']);
// Route::post('serviceOrders', ['as'=> 'serviceOrders.store', 'uses' => 'Service Order\Service OrderController@store']);
// Route::get('serviceOrders/create', ['as'=> 'serviceOrders.create', 'uses' => 'Service Order\Service OrderController@create']);
// Route::put('serviceOrders/{serviceOrders}', ['as'=> 'serviceOrders.update', 'uses' => 'Service Order\Service OrderController@update']);
// Route::patch('serviceOrders/{serviceOrders}', ['as'=> 'serviceOrders.update', 'uses' => 'Service Order\Service OrderController@update']);
// Route::get('serviceOrders/{id}/delete', ['as' => 'serviceOrders.delete', 'uses' => 'Service Order\Service OrderController@getDelete']);
// Route::get('serviceOrders/{id}/confirm-delete', ['as' => 'serviceOrders.confirm-delete', 'uses' => 'Service Order\Service OrderController@getModalDelete']);
// Route::get('serviceOrders/{serviceOrders}', ['as'=> 'serviceOrders.show', 'uses' => 'Service Order\Service OrderController@show']);
// Route::get('serviceOrders/{serviceOrders}/edit', ['as'=> 'serviceOrders.edit', 'uses' => 'Service Order\Service OrderController@edit']);

// });


// Route::group(array('prefix' => 'admin/serviceOrders/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.serviceOrders.'), function () {

// Route::get('serviceOrders', ['as'=> 'serviceOrders.index', 'uses' => 'Service Orders\ServiceOrdersController@index']);
// Route::post('serviceOrders', ['as'=> 'serviceOrders.store', 'uses' => 'Service Orders\ServiceOrdersController@store']);
// Route::get('serviceOrders/create', ['as'=> 'serviceOrders.create', 'uses' => 'Service Orders\ServiceOrdersController@create']);
// Route::put('serviceOrders/{serviceOrders}', ['as'=> 'serviceOrders.update', 'uses' => 'Service Orders\ServiceOrdersController@update']);
// Route::patch('serviceOrders/{serviceOrders}', ['as'=> 'serviceOrders.update', 'uses' => 'Service Orders\ServiceOrdersController@update']);
// Route::get('serviceOrders/{id}/delete', ['as' => 'serviceOrders.delete', 'uses' => 'Service Orders\ServiceOrdersController@getDelete']);
// Route::get('serviceOrders/{id}/confirm-delete', ['as' => 'serviceOrders.confirm-delete', 'uses' => 'Service Orders\ServiceOrdersController@getModalDelete']);
// Route::get('serviceOrders/{serviceOrders}', ['as'=> 'serviceOrders.show', 'uses' => 'Service Orders\ServiceOrdersController@show']);
// Route::get('serviceOrders/{serviceOrders}/edit', ['as'=> 'serviceOrders.edit', 'uses' => 'Service Orders\ServiceOrdersController@edit']);

// });


Route::group(array('prefix' => 'admin/serviceOrders/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.serviceOrders.'), function () {

Route::get('serviceOrders', ['as'=> 'serviceOrders.index', 'uses' => 'Serviceorders\ServiceOrdersController@index']);
Route::get('deactivate_service', ['as'=> 'serviceOrders.deactivate_service', 'uses' => 'Serviceorders\ServiceOrdersController@deactivate_service']);
Route::post('serviceOrders', ['as'=> 'serviceOrders.store', 'uses' => 'Serviceorders\ServiceOrdersController@store']);
Route::get('serviceOrders/create', ['as'=> 'serviceOrders.create', 'uses' => 'Serviceorders\ServiceOrdersController@create']);
Route::put('serviceOrders/{serviceOrders}', ['as'=> 'serviceOrders.update', 'uses' => 'Serviceorders\ServiceOrdersController@update']);
Route::patch('serviceOrders/{serviceOrders}', ['as'=> 'serviceOrders.update', 'uses' => 'Serviceorders\ServiceOrdersController@update']);
Route::get('serviceOrders/{id}/delete', ['as' => 'serviceOrders.delete', 'uses' => 'Serviceorders\ServiceOrdersController@getDelete']);
Route::get('serviceOrders/{id}/confirm-delete', ['as' => 'serviceOrders.confirm-delete', 'uses' => 'Serviceorders\ServiceOrdersController@getModalDelete']);
Route::get('serviceOrders/{serviceOrders}', ['as'=> 'serviceOrders.show', 'uses' => 'Serviceorders\ServiceOrdersController@show']);
Route::get('serviceOrders/{serviceOrders}/edit', ['as'=> 'serviceOrders.edit', 'uses' => 'Serviceorders\ServiceOrdersController@edit']);

});


Route::group(array('prefix' => 'admin/productType/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.productType.'), function () {

Route::get('productTypes', ['as'=> 'productTypes.index', 'uses' => 'Producttype\ProductTypeController@index']);
Route::post('productTypes', ['as'=> 'productTypes.store', 'uses' => 'Producttype\ProductTypeController@store']);
Route::get('productTypes/create', ['as'=> 'productTypes.create', 'uses' => 'Producttype\ProductTypeController@create']);
Route::put('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Producttype\ProductTypeController@update']);
Route::patch('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Producttype\ProductTypeController@update']);
Route::get('productTypes/{id}/delete', ['as' => 'productTypes.delete', 'uses' => 'Producttype\ProductTypeController@getDelete']);
Route::get('productTypes/{id}/confirm-delete', ['as' => 'productTypes.confirm-delete', 'uses' => 'Producttype\ProductTypeController@getModalDelete']);
Route::get('productTypes/{productTypes}', ['as'=> 'productTypes.show', 'uses' => 'Producttype\ProductTypeController@show']);
Route::get('productTypes/{productTypes}/edit', ['as'=> 'productTypes.edit', 'uses' => 'Producttype\ProductTypeController@edit']);

});


Route::group(array('prefix' => 'admin/paymentMode/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.paymentMode.'), function () {

Route::get('paymentModes', ['as'=> 'paymentModes.index', 'uses' => 'Paymentmode\PaymentModeController@index']);
Route::post('paymentModes', ['as'=> 'paymentModes.store', 'uses' => 'Paymentmode\PaymentModeController@store']);
Route::get('paymentModes/create', ['as'=> 'paymentModes.create', 'uses' => 'Paymentmode\PaymentModeController@create']);
Route::put('paymentModes/{paymentModes}', ['as'=> 'paymentModes.update', 'uses' => 'Paymentmode\PaymentModeController@update']);
Route::patch('paymentModes/{paymentModes}', ['as'=> 'paymentModes.update', 'uses' => 'Paymentmode\PaymentModeController@update']);
Route::get('paymentModes/{id}/delete', ['as' => 'paymentModes.delete', 'uses' => 'Paymentmode\PaymentModeController@getDelete']);
Route::get('paymentModes/{id}/confirm-delete', ['as' => 'paymentModes.confirm-delete', 'uses' => 'Paymentmode\PaymentModeController@getModalDelete']);
Route::get('paymentModes/{paymentModes}', ['as'=> 'paymentModes.show', 'uses' => 'Paymentmode\PaymentModeController@show']);
Route::get('paymentModes/{paymentModes}/edit', ['as'=> 'paymentModes.edit', 'uses' => 'Paymentmode\PaymentModeController@edit']);

});


Route::group(array('prefix' => 'admin/unitofMeasure/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.unitofMeasure.'), function () {

Route::get('unitofMeasures', ['as'=> 'unitofMeasures.index', 'uses' => 'Unitofmeasure\UnitofMeasureController@index']);
Route::post('unitofMeasures', ['as'=> 'unitofMeasures.store', 'uses' => 'Unitofmeasure\UnitofMeasureController@store']);
Route::get('unitofMeasures/create', ['as'=> 'unitofMeasures.create', 'uses' => 'Unitofmeasure\UnitofMeasureController@create']);
Route::put('unitofMeasures/{unitofMeasures}', ['as'=> 'unitofMeasures.update', 'uses' => 'Unitofmeasure\UnitofMeasureController@update']);
Route::patch('unitofMeasures/{unitofMeasures}', ['as'=> 'unitofMeasures.update', 'uses' => 'Unitofmeasure\UnitofMeasureController@update']);
Route::get('unitofMeasures/{id}/delete', ['as' => 'unitofMeasures.delete', 'uses' => 'Unitofmeasure\UnitofMeasureController@getDelete']);
Route::get('unitofMeasures/{id}/confirm-delete', ['as' => 'unitofMeasures.confirm-delete', 'uses' => 'Unitofmeasure\UnitofMeasureController@getModalDelete']);
Route::get('unitofMeasures/{unitofMeasures}', ['as'=> 'unitofMeasures.show', 'uses' => 'Unitofmeasure\UnitofMeasureController@show']);
Route::get('unitofMeasures/{unitofMeasures}/edit', ['as'=> 'unitofMeasures.edit', 'uses' => 'Unitofmeasure\UnitofMeasureController@edit']);

});


Route::group(array('prefix' => 'admin/customerType/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.customerType.'), function () {

Route::get('customerTypes', ['as'=> 'customerTypes.index', 'uses' => 'Customertype\CustomerTypeController@index']);
Route::post('customerTypes', ['as'=> 'customerTypes.store', 'uses' => 'Customertype\CustomerTypeController@store']);
Route::get('customerTypes/create', ['as'=> 'customerTypes.create', 'uses' => 'Customertype\CustomerTypeController@create']);
Route::put('customerTypes/{customerTypes}', ['as'=> 'customerTypes.update', 'uses' => 'Customertype\CustomerTypeController@update']);
Route::patch('customerTypes/{customerTypes}', ['as'=> 'customerTypes.update', 'uses' => 'Customertype\CustomerTypeController@update']);
Route::get('customerTypes/{id}/delete', ['as' => 'customerTypes.delete', 'uses' => 'Customertype\CustomerTypeController@getDelete']);
Route::get('customerTypes/{id}/confirm-delete', ['as' => 'customerTypes.confirm-delete', 'uses' => 'Customertype\CustomerTypeController@getModalDelete']);
Route::get('customerTypes/{customerTypes}', ['as'=> 'customerTypes.show', 'uses' => 'Customertype\CustomerTypeController@show']);
Route::get('customerTypes/{customerTypes}/edit', ['as'=> 'customerTypes.edit', 'uses' => 'Customertype\CustomerTypeController@edit']);

});


Route::group(array('prefix' => 'admin/paymentMode/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.paymentMode.'), function () {

Route::get('paymentModes', ['as'=> 'paymentModes.index', 'uses' => 'Paymentmode\PaymentModeController@index']);
Route::post('paymentModes', ['as'=> 'paymentModes.store', 'uses' => 'Paymentmode\PaymentModeController@store']);
Route::get('paymentModes/create', ['as'=> 'paymentModes.create', 'uses' => 'Paymentmode\PaymentModeController@create']);
Route::put('paymentModes/{paymentModes}', ['as'=> 'paymentModes.update', 'uses' => 'Paymentmode\PaymentModeController@update']);
Route::patch('paymentModes/{paymentModes}', ['as'=> 'paymentModes.update', 'uses' => 'Paymentmode\PaymentModeController@update']);
Route::get('paymentModes/{id}/delete', ['as' => 'paymentModes.delete', 'uses' => 'Paymentmode\PaymentModeController@getDelete']);
Route::get('paymentModes/{id}/confirm-delete', ['as' => 'paymentModes.confirm-delete', 'uses' => 'Paymentmode\PaymentModeController@getModalDelete']);
Route::get('paymentModes/{paymentModes}', ['as'=> 'paymentModes.show', 'uses' => 'Paymentmode\PaymentModeController@show']);
Route::get('paymentModes/{paymentModes}/edit', ['as'=> 'paymentModes.edit', 'uses' => 'Paymentmode\PaymentModeController@edit']);

});


Route::group(array('prefix' => 'admin/servicestatus/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.servicestatus.'), function () {

Route::get('servicestatuses', ['as'=> 'servicestatuses.index', 'uses' => 'Servicestatus\ServicestatusController@index']);
Route::post('servicestatuses', ['as'=> 'servicestatuses.store', 'uses' => 'Servicestatus\ServicestatusController@store']);
Route::get('servicestatuses/create', ['as'=> 'servicestatuses.create', 'uses' => 'Servicestatus\ServicestatusController@create']);
Route::put('servicestatuses/{servicestatuses}', ['as'=> 'servicestatuses.update', 'uses' => 'Servicestatus\ServicestatusController@update']);
Route::patch('servicestatuses/{servicestatuses}', ['as'=> 'servicestatuses.update', 'uses' => 'Servicestatus\ServicestatusController@update']);
Route::get('servicestatuses/{id}/delete', ['as' => 'servicestatuses.delete', 'uses' => 'Servicestatus\ServicestatusController@getDelete']);
Route::get('servicestatuses/{id}/confirm-delete', ['as' => 'servicestatuses.confirm-delete', 'uses' => 'Servicestatus\ServicestatusController@getModalDelete']);
Route::get('servicestatuses/{servicestatuses}', ['as'=> 'servicestatuses.show', 'uses' => 'Servicestatus\ServicestatusController@show']);
Route::get('servicestatuses/{servicestatuses}/edit', ['as'=> 'servicestatuses.edit', 'uses' => 'Servicestatus\ServicestatusController@edit']);

});


Route::group(array('prefix' => 'admin/serviceBilling/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.serviceBilling.'), function () {

Route::get('serviceBillings', ['as'=> 'serviceBillings.index', 'uses' => 'Servicebilling\ServiceBillingController@index']);
Route::post('serviceBillings', ['as'=> 'serviceBillings.store', 'uses' => 'Servicebilling\ServiceBillingController@store']);
Route::get('serviceBillings/create', ['as'=> 'serviceBillings.create', 'uses' => 'Servicebilling\ServiceBillingController@create']);
Route::put('serviceBillings/{serviceBillings}', ['as'=> 'serviceBillings.update', 'uses' => 'Servicebilling\ServiceBillingController@update']);
Route::patch('serviceBillings/{serviceBillings}', ['as'=> 'serviceBillings.update', 'uses' => 'Servicebilling\ServiceBillingController@update']);
Route::get('serviceBillings/{id}/delete', ['as' => 'serviceBillings.delete', 'uses' => 'Servicebilling\ServiceBillingController@getDelete']);
Route::get('serviceBillings/{id}/confirm-delete', ['as' => 'serviceBillings.confirm-delete', 'uses' => 'Servicebilling\ServiceBillingController@getModalDelete']);
Route::get('serviceBillings/{serviceBillings}', ['as'=> 'serviceBillings.show', 'uses' => 'Servicebilling\ServiceBillingController@show']);
Route::get('serviceBillings/{serviceBillings}/edit', ['as'=> 'serviceBillings.edit', 'uses' => 'Servicebilling\ServiceBillingController@edit']);

});


Route::group(array('prefix' => 'admin/serviceInvoice/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.serviceInvoice.'), function () {

Route::get('serviceInvoices', ['as'=> 'serviceInvoices.index', 'uses' => 'Serviceinvoice\ServiceInvoiceController@index']);
Route::post('serviceInvoices', ['as'=> 'serviceInvoices.store', 'uses' => 'Serviceinvoice\ServiceInvoiceController@store']);
Route::post('nidcConfigs/traapi', ['as'=> 'serviceInvoices.traapi', 'uses' => 'Serviceinvoice\ServiceInvoiceController@processTraReceipt']);
Route::get('nidcConfigs/post_tra_reg', ['as'=> 'serviceInvoices.post_tra_reg', 'uses' => 'Serviceinvoice\ServiceInvoiceController@post_tra_reg']);
Route::get('serviceInvoices/create', ['as'=> 'serviceInvoices.create', 'uses' => 'Serviceinvoice\ServiceInvoiceController@create']);
Route::put('serviceInvoices/{serviceInvoices}', ['as'=> 'serviceInvoices.update', 'uses' => 'Serviceinvoice\ServiceInvoiceController@update']);
Route::patch('serviceInvoices/{serviceInvoices}', ['as'=> 'serviceInvoices.update', 'uses' => 'Serviceinvoice\ServiceInvoiceController@update']);
Route::get('serviceInvoices/{id}/delete', ['as' => 'serviceInvoices.delete', 'uses' => 'Serviceinvoice\ServiceInvoiceController@getDelete']);
Route::get('serviceInvoices/{id}/confirm-delete', ['as' => 'serviceInvoices.confirm-delete', 'uses' => 'Serviceinvoice\ServiceInvoiceController@getModalDelete']);
Route::get('serviceInvoices/{serviceInvoices}', ['as'=> 'serviceInvoices.show', 'uses' => 'Serviceinvoice\ServiceInvoiceController@show']);
Route::get('serviceInvoices/{serviceInvoices}/edit', ['as'=> 'serviceInvoices.edit', 'uses' => 'Serviceinvoice\ServiceInvoiceController@edit']);
Route::get('auto_invoice_generator', ['as'=> 'serviceInvoices.auto_invoice_generator', 'uses' => 'Serviceinvoice\ServiceInvoiceController@auto_invoice_generator']);

});


Route::group(array('prefix' => 'admin/paymentType/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.paymentType.'), function () {

Route::get('paymentTypes', ['as'=> 'paymentTypes.index', 'uses' => 'Paymenttype\PaymentTypeController@index']);
Route::post('paymentTypes', ['as'=> 'paymentTypes.store', 'uses' => 'Paymenttype\PaymentTypeController@store']);
Route::get('paymentTypes/create', ['as'=> 'paymentTypes.create', 'uses' => 'Paymenttype\PaymentTypeController@create']);
Route::put('paymentTypes/{paymentTypes}', ['as'=> 'paymentTypes.update', 'uses' => 'Paymenttype\PaymentTypeController@update']);
Route::patch('paymentTypes/{paymentTypes}', ['as'=> 'paymentTypes.update', 'uses' => 'Paymenttype\PaymentTypeController@update']);
Route::get('paymentTypes/{id}/delete', ['as' => 'paymentTypes.delete', 'uses' => 'Paymenttype\PaymentTypeController@getDelete']);
Route::get('paymentTypes/{id}/confirm-delete', ['as' => 'paymentTypes.confirm-delete', 'uses' => 'Paymenttype\PaymentTypeController@getModalDelete']);
Route::get('paymentTypes/{paymentTypes}', ['as'=> 'paymentTypes.show', 'uses' => 'Paymenttype\PaymentTypeController@show']);
Route::get('paymentTypes/{paymentTypes}/edit', ['as'=> 'paymentTypes.edit', 'uses' => 'Paymenttype\PaymentTypeController@edit']);

});


Route::group(array('prefix' => 'admin/paymentAndDue/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.paymentAndDue.'), function () {

Route::get('paymentAndDues', ['as'=> 'paymentAndDues.index', 'uses' => 'Paymentanddue\PaymentAndDueController@index']);
Route::post('paymentAndDues', ['as'=> 'paymentAndDues.store', 'uses' => 'Paymentanddue\PaymentAndDueController@store']);
Route::get('paymentAndDues/create', ['as'=> 'paymentAndDues.create', 'uses' => 'Paymentanddue\PaymentAndDueController@create']);
Route::put('paymentAndDues/{paymentAndDues}', ['as'=> 'paymentAndDues.update', 'uses' => 'Paymentanddue\PaymentAndDueController@update']);
Route::patch('paymentAndDues/{paymentAndDues}', ['as'=> 'paymentAndDues.update', 'uses' => 'Paymentanddue\PaymentAndDueController@update']);
Route::get('paymentAndDues/{id}/delete', ['as' => 'paymentAndDues.delete', 'uses' => 'Paymentanddue\PaymentAndDueController@getDelete']);
Route::get('paymentAndDues/{id}/confirm-delete', ['as' => 'paymentAndDues.confirm-delete', 'uses' => 'Paymentanddue\PaymentAndDueController@getModalDelete']);
Route::get('paymentAndDues/{paymentAndDues}', ['as'=> 'paymentAndDues.show', 'uses' => 'Paymentanddue\PaymentAndDueController@show']);
Route::get('paymentAndDues/{paymentAndDues}/edit', ['as'=> 'paymentAndDues.edit', 'uses' => 'Paymentanddue\PaymentAndDueController@edit']);

});


Route::group(array('prefix' => 'admin/invoicwePayment/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.invoicwePayment.'), function () {

Route::get('invoicwePayments', ['as'=> 'invoicwePayments.index', 'uses' => 'Invoicwepayment\InvoicwePaymentController@index']);
Route::post('invoicwePayments', ['as'=> 'invoicwePayments.store', 'uses' => 'Invoicwepayment\InvoicwePaymentController@store']);
Route::get('invoicwePayments/create', ['as'=> 'invoicwePayments.create', 'uses' => 'Invoicwepayment\InvoicwePaymentController@create']);
Route::put('invoicwePayments/{invoicwePayments}', ['as'=> 'invoicwePayments.update', 'uses' => 'Invoicwepayment\InvoicwePaymentController@update']);
Route::patch('invoicwePayments/{invoicwePayments}', ['as'=> 'invoicwePayments.update', 'uses' => 'Invoicwepayment\InvoicwePaymentController@update']);
Route::get('invoicwePayments/{id}/delete', ['as' => 'invoicwePayments.delete', 'uses' => 'Invoicwepayment\InvoicwePaymentController@getDelete']);
Route::get('invoicwePayments/{id}/confirm-delete', ['as' => 'invoicwePayments.confirm-delete', 'uses' => 'Invoicwepayment\InvoicwePaymentController@getModalDelete']);
Route::get('invoicwePayments/{invoicwePayments}', ['as'=> 'invoicwePayments.show', 'uses' => 'Invoicwepayment\InvoicwePaymentController@show']);
Route::get('invoicwePayments/{invoicwePayments}/edit', ['as'=> 'invoicwePayments.edit', 'uses' => 'Invoicwepayment\InvoicwePaymentController@edit']);

});


Route::group(array('prefix' => 'admin/serviceOrderType/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.serviceOrderType.'), function () {

Route::get('serviceOrderTypes', ['as'=> 'serviceOrderTypes.index', 'uses' => 'Serviceordertype\ServiceOrderTypeController@index']);
Route::post('serviceOrderTypes', ['as'=> 'serviceOrderTypes.store', 'uses' => 'Serviceordertype\ServiceOrderTypeController@store']);
Route::get('serviceOrderTypes/create', ['as'=> 'serviceOrderTypes.create', 'uses' => 'Serviceordertype\ServiceOrderTypeController@create']);
Route::put('serviceOrderTypes/{serviceOrderTypes}', ['as'=> 'serviceOrderTypes.update', 'uses' => 'Serviceordertype\ServiceOrderTypeController@update']);
Route::patch('serviceOrderTypes/{serviceOrderTypes}', ['as'=> 'serviceOrderTypes.update', 'uses' => 'Serviceordertype\ServiceOrderTypeController@update']);
Route::get('serviceOrderTypes/{id}/delete', ['as' => 'serviceOrderTypes.delete', 'uses' => 'Serviceordertype\ServiceOrderTypeController@getDelete']);
Route::get('serviceOrderTypes/{id}/confirm-delete', ['as' => 'serviceOrderTypes.confirm-delete', 'uses' => 'Serviceordertype\ServiceOrderTypeController@getModalDelete']);
Route::get('serviceOrderTypes/{serviceOrderTypes}', ['as'=> 'serviceOrderTypes.show', 'uses' => 'Serviceordertype\ServiceOrderTypeController@show']);
Route::get('serviceOrderTypes/{serviceOrderTypes}/edit', ['as'=> 'serviceOrderTypes.edit', 'uses' => 'Serviceordertype\ServiceOrderTypeController@edit']);

});


Route::group(array('prefix' => 'admin/comment/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.comment.'), function () {

Route::get('comments', ['as'=> 'comments.index', 'uses' => 'Comment\CommentController@index']);
Route::post('comments', ['as'=> 'comments.store', 'uses' => 'Comment\CommentController@store']);
Route::get('comments/create', ['as'=> 'comments.create', 'uses' => 'Comment\CommentController@create']);
Route::put('comments/{comments}', ['as'=> 'comments.update', 'uses' => 'Comment\CommentController@update']);
Route::patch('comments/{comments}', ['as'=> 'comments.update', 'uses' => 'Comment\CommentController@update']);
Route::get('comments/{id}/delete', ['as' => 'comments.delete', 'uses' => 'Comment\CommentController@getDelete']);
Route::get('comments/{id}/confirm-delete', ['as' => 'comments.confirm-delete', 'uses' => 'Comment\CommentController@getModalDelete']);
Route::get('comments/{comments}', ['as'=> 'comments.show', 'uses' => 'Comment\CommentController@show']);
Route::get('comments/{comments}/edit', ['as'=> 'comments.edit', 'uses' => 'Comment\CommentController@edit']);

});


Route::group(array('prefix' => 'admin/creditNote/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.creditNote.'), function () {

Route::get('creditNotes', ['as'=> 'creditNotes.index', 'uses' => 'Creditnote\CreditNoteController@index']);
Route::post('creditNotes', ['as'=> 'creditNotes.store', 'uses' => 'Creditnote\CreditNoteController@store']);
Route::get('creditNotes/create', ['as'=> 'creditNotes.create', 'uses' => 'Creditnote\CreditNoteController@create']);
Route::put('creditNotes/{creditNotes}', ['as'=> 'creditNotes.update', 'uses' => 'Creditnote\CreditNoteController@update']);
Route::patch('creditNotes/{creditNotes}', ['as'=> 'creditNotes.update', 'uses' => 'Creditnote\CreditNoteController@update']);
Route::get('creditNotes/{id}/delete', ['as' => 'creditNotes.delete', 'uses' => 'Creditnote\CreditNoteController@getDelete']);
Route::get('creditNotes/{id}/confirm-delete', ['as' => 'creditNotes.confirm-delete', 'uses' => 'Creditnote\CreditNoteController@getModalDelete']);
Route::get('creditNotes/{creditNotes}', ['as'=> 'creditNotes.show', 'uses' => 'Creditnote\CreditNoteController@show']);
Route::get('creditNotes/{creditNotes}/edit', ['as'=> 'creditNotes.edit', 'uses' => 'Creditnote\CreditNoteController@edit']);

});


Route::group(array('prefix' => 'admin/agingAnalysisReport/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.agingAnalysisReport.'), function () {

Route::get('agingAnalysisReports', ['as'=> 'agingAnalysisReports.index', 'uses' => 'Aginganalysisreport\AgingAnalysisReportController@index']);
Route::post('agingAnalysisReports', ['as'=> 'agingAnalysisReports.store', 'uses' => 'Aginganalysisreport\AgingAnalysisReportController@store']);
Route::get('agingAnalysisReports/create', ['as'=> 'agingAnalysisReports.create', 'uses' => 'Aginganalysisreport\AgingAnalysisReportController@create']);
Route::put('agingAnalysisReports/{agingAnalysisReports}', ['as'=> 'agingAnalysisReports.update', 'uses' => 'Aginganalysisreport\AgingAnalysisReportController@update']);
Route::patch('agingAnalysisReports/{agingAnalysisReports}', ['as'=> 'agingAnalysisReports.update', 'uses' => 'Aginganalysisreport\AgingAnalysisReportController@update']);
Route::get('agingAnalysisReports/{id}/delete', ['as' => 'agingAnalysisReports.delete', 'uses' => 'Aginganalysisreport\AgingAnalysisReportController@getDelete']);
Route::get('agingAnalysisReports/{id}/confirm-delete', ['as' => 'agingAnalysisReports.confirm-delete', 'uses' => 'Aginganalysisreport\AgingAnalysisReportController@getModalDelete']);
Route::get('agingAnalysisReports/{agingAnalysisReports}', ['as'=> 'agingAnalysisReports.show', 'uses' => 'Aginganalysisreport\AgingAnalysisReportController@show']);
Route::get('agingAnalysisReports/{agingAnalysisReports}/edit', ['as'=> 'agingAnalysisReports.edit', 'uses' => 'Aginganalysisreport\AgingAnalysisReportController@edit']);

});


Route::group(array('prefix' => 'admin/revenuePerCustomerReport/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.revenuePerCustomerReport.'), function () {

Route::get('revenuePerCustomerReports', ['as'=> 'revenuePerCustomerReports.index', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@index']);
Route::get('datepicker', ['as'=> 'revenuePerCustomerReports.datepicker', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@datepicker']);
Route::post('revenuePerCustomerReports', ['as'=> 'revenuePerCustomerReports.store', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@store']);
Route::get('revenuePerCustomerReports/create', ['as'=> 'revenuePerCustomerReports.create', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@create']);
Route::put('revenuePerCustomerReports/{revenuePerCustomerReports}', ['as'=> 'revenuePerCustomerReports.update', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@update']);
Route::patch('revenuePerCustomerReports/{revenuePerCustomerReports}', ['as'=> 'revenuePerCustomerReports.update', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@update']);
Route::get('revenuePerCustomerReports/{id}/delete', ['as' => 'revenuePerCustomerReports.delete', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@getDelete']);
Route::get('revenuePerCustomerReports/{id}/confirm-delete', ['as' => 'revenuePerCustomerReports.confirm-delete', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@getModalDelete']);
Route::get('revenuePerCustomerReports/{revenuePerCustomerReports}', ['as'=> 'revenuePerCustomerReports.show', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@show']);
Route::get('revenuePerCustomerReports/{revenuePerCustomerReports}/edit', ['as'=> 'revenuePerCustomerReports.edit', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@edit']);

});


Route::group(array('prefix' => 'admin/traDetailsConf/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.traDetailsConf.'), function () {

Route::get('traDetailsConfs', ['as'=> 'traDetailsConfs.index', 'uses' => 'Tra_Details_Conf\Tra_details_confController@index']);
Route::post('traDetailsConfs', ['as'=> 'traDetailsConfs.store', 'uses' => 'Tra_Details_Conf\Tra_details_confController@store']);
Route::get('traDetailsConfs/create', ['as'=> 'traDetailsConfs.create', 'uses' => 'Tra_Details_Conf\Tra_details_confController@create']);
Route::put('traDetailsConfs/{traDetailsConfs}', ['as'=> 'traDetailsConfs.update', 'uses' => 'Tra_Details_Conf\Tra_details_confController@update']);
Route::patch('traDetailsConfs/{traDetailsConfs}', ['as'=> 'traDetailsConfs.update', 'uses' => 'Tra_Details_Conf\Tra_details_confController@update']);
Route::get('traDetailsConfs/{id}/delete', ['as' => 'traDetailsConfs.delete', 'uses' => 'Tra_Details_Conf\Tra_details_confController@getDelete']);
Route::get('traDetailsConfs/{id}/confirm-delete', ['as' => 'traDetailsConfs.confirm-delete', 'uses' => 'Tra_Details_Conf\Tra_details_confController@getModalDelete']);
Route::get('traDetailsConfs/{traDetailsConfs}', ['as'=> 'traDetailsConfs.show', 'uses' => 'Tra_Details_Conf\Tra_details_confController@show']);
Route::get('traDetailsConfs/{traDetailsConfs}/edit', ['as'=> 'traDetailsConfs.edit', 'uses' => 'Tra_Details_Conf\Tra_details_confController@edit']);

});


Route::group(array('prefix' => 'admin/traDetailsConf/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.traDetailsConf.'), function () {

Route::get('traDetailsConfs', ['as'=> 'traDetailsConfs.index', 'uses' => 'Tra_Details_Conf\Tra_details_confController@index']);
Route::post('traDetailsConfs', ['as'=> 'traDetailsConfs.store', 'uses' => 'Tra_Details_Conf\Tra_details_confController@store']);
Route::get('traDetailsConfs/create', ['as'=> 'traDetailsConfs.create', 'uses' => 'Tra_Details_Conf\Tra_details_confController@create']);
Route::put('traDetailsConfs/{traDetailsConfs}', ['as'=> 'traDetailsConfs.update', 'uses' => 'Tra_Details_Conf\Tra_details_confController@update']);
Route::patch('traDetailsConfs/{traDetailsConfs}', ['as'=> 'traDetailsConfs.update', 'uses' => 'Tra_Details_Conf\Tra_details_confController@update']);
Route::get('traDetailsConfs/{id}/delete', ['as' => 'traDetailsConfs.delete', 'uses' => 'Tra_Details_Conf\Tra_details_confController@getDelete']);
Route::get('traDetailsConfs/{id}/confirm-delete', ['as' => 'traDetailsConfs.confirm-delete', 'uses' => 'Tra_Details_Conf\Tra_details_confController@getModalDelete']);
Route::get('traDetailsConfs/{traDetailsConfs}', ['as'=> 'traDetailsConfs.show', 'uses' => 'Tra_Details_Conf\Tra_details_confController@show']);
Route::get('traDetailsConfs/{traDetailsConfs}/edit', ['as'=> 'traDetailsConfs.edit', 'uses' => 'Tra_Details_Conf\Tra_details_confController@edit']);

});


Route::group(array('prefix' => 'admin/traDetailsConf/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.traDetailsConf.'), function () {

Route::get('tradetailsconfs', ['as'=> 'tradetailsconfs.index', 'uses' => 'Tra_Details_Conf\TradetailsconfController@index']);
Route::post('tradetailsconfs', ['as'=> 'tradetailsconfs.store', 'uses' => 'Tra_Details_Conf\TradetailsconfController@store']);
Route::get('tradetailsconfs/create', ['as'=> 'tradetailsconfs.create', 'uses' => 'Tra_Details_Conf\TradetailsconfController@create']);
Route::put('tradetailsconfs/{tradetailsconfs}', ['as'=> 'tradetailsconfs.update', 'uses' => 'Tra_Details_Conf\TradetailsconfController@update']);
Route::patch('tradetailsconfs/{tradetailsconfs}', ['as'=> 'tradetailsconfs.update', 'uses' => 'Tra_Details_Conf\TradetailsconfController@update']);
Route::get('tradetailsconfs/{id}/delete', ['as' => 'tradetailsconfs.delete', 'uses' => 'Tra_Details_Conf\TradetailsconfController@getDelete']);
Route::get('tradetailsconfs/{id}/confirm-delete', ['as' => 'tradetailsconfs.confirm-delete', 'uses' => 'Tra_Details_Conf\TradetailsconfController@getModalDelete']);
Route::get('tradetailsconfs/{tradetailsconfs}', ['as'=> 'tradetailsconfs.show', 'uses' => 'Tra_Details_Conf\TradetailsconfController@show']);
Route::get('tradetailsconfs/{tradetailsconfs}/edit', ['as'=> 'tradetailsconfs.edit', 'uses' => 'Tra_Details_Conf\TradetailsconfController@edit']);

});


Route::group(array('prefix' => 'admin/traDetailsConf/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.traDetailsConf.'), function () {

Route::get('tradetailsconfs', ['as'=> 'tradetailsconfs.index', 'uses' => 'Tra_Details_Conf\TradetailsconfController@index']);
Route::post('tradetailsconfs', ['as'=> 'tradetailsconfs.store', 'uses' => 'Tra_Details_Conf\TradetailsconfController@store']);
Route::get('tradetailsconfs/create', ['as'=> 'tradetailsconfs.create', 'uses' => 'Tra_Details_Conf\TradetailsconfController@create']);
Route::put('tradetailsconfs/{tradetailsconfs}', ['as'=> 'tradetailsconfs.update', 'uses' => 'Tra_Details_Conf\TradetailsconfController@update']);
Route::patch('tradetailsconfs/{tradetailsconfs}', ['as'=> 'tradetailsconfs.update', 'uses' => 'Tra_Details_Conf\TradetailsconfController@update']);
Route::get('tradetailsconfs/{id}/delete', ['as' => 'tradetailsconfs.delete', 'uses' => 'Tra_Details_Conf\TradetailsconfController@getDelete']);
Route::get('tradetailsconfs/{id}/confirm-delete', ['as' => 'tradetailsconfs.confirm-delete', 'uses' => 'Tra_Details_Conf\TradetailsconfController@getModalDelete']);
Route::get('tradetailsconfs/{tradetailsconfs}', ['as'=> 'tradetailsconfs.show', 'uses' => 'Tra_Details_Conf\TradetailsconfController@show']);
Route::get('tradetailsconfs/{tradetailsconfs}/edit', ['as'=> 'tradetailsconfs.edit', 'uses' => 'Tra_Details_Conf\TradetailsconfController@edit']);

});


Route::group(array('prefix' => 'admin/traDetailsConf/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.traDetailsConf.'), function () {

Route::get('tradetailsconfs', ['as'=> 'tradetailsconfs.index', 'uses' => 'Tradetailsconf\TradetailsconfController@index']);
Route::post('tradetailsconfs', ['as'=> 'tradetailsconfs.store', 'uses' => 'Tradetailsconf\TradetailsconfController@store']);
Route::get('tradetailsconfs/create', ['as'=> 'tradetailsconfs.create', 'uses' => 'Tradetailsconf\TradetailsconfController@create']);
Route::put('tradetailsconfs/{tradetailsconfs}', ['as'=> 'tradetailsconfs.update', 'uses' => 'Tradetailsconf\TradetailsconfController@update']);
Route::patch('tradetailsconfs/{tradetailsconfs}', ['as'=> 'tradetailsconfs.update', 'uses' => 'Tradetailsconf\TradetailsconfController@update']);
Route::get('tradetailsconfs/{id}/delete', ['as' => 'tradetailsconfs.delete', 'uses' => 'Tradetailsconf\TradetailsconfController@getDelete']);
Route::get('tradetailsconfs/{id}/confirm-delete', ['as' => 'tradetailsconfs.confirm-delete', 'uses' => 'Tradetailsconf\TradetailsconfController@getModalDelete']);
Route::get('tradetailsconfs/{tradetailsconfs}', ['as'=> 'tradetailsconfs.show', 'uses' => 'Tradetailsconf\TradetailsconfController@show']);
Route::get('tradetailsconfs/{tradetailsconfs}/edit', ['as'=> 'tradetailsconfs.edit', 'uses' => 'Tradetailsconf\TradetailsconfController@edit']);

});


Route::group(array('prefix' => 'admin/traDetailsConf/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.traDetailsConf.'), function () {

Route::get('companyDetails', ['as'=> 'companyDetails.index', 'uses' => 'Tradetailsconf\CompanyDetailsController@index']);
Route::post('companyDetails', ['as'=> 'companyDetails.store', 'uses' => 'Tradetailsconf\CompanyDetailsController@store']);
Route::get('companyDetails/create', ['as'=> 'companyDetails.create', 'uses' => 'Tradetailsconf\CompanyDetailsController@create']);
Route::put('companyDetails/{companyDetails}', ['as'=> 'companyDetails.update', 'uses' => 'Tradetailsconf\CompanyDetailsController@update']);
Route::patch('companyDetails/{companyDetails}', ['as'=> 'companyDetails.update', 'uses' => 'Tradetailsconf\CompanyDetailsController@update']);
Route::get('companyDetails/{id}/delete', ['as' => 'companyDetails.delete', 'uses' => 'Tradetailsconf\CompanyDetailsController@getDelete']);
Route::get('companyDetails/{id}/confirm-delete', ['as' => 'companyDetails.confirm-delete', 'uses' => 'Tradetailsconf\CompanyDetailsController@getModalDelete']);
Route::get('companyDetails/{companyDetails}', ['as'=> 'companyDetails.show', 'uses' => 'Tradetailsconf\CompanyDetailsController@show']);
Route::get('companyDetails/{companyDetails}/edit', ['as'=> 'companyDetails.edit', 'uses' => 'Tradetailsconf\CompanyDetailsController@edit']);

});


Route::group(array('prefix' => 'admin/traDetailsConf/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.traDetailsConf.'), function () {

Route::get('companyDetails', ['as'=> 'companyDetails.index', 'uses' => 'Tradetailsconf\CompanyDetailsController@index']);
Route::post('companyDetails', ['as'=> 'companyDetails.store', 'uses' => 'Tradetailsconf\CompanyDetailsController@store']);
Route::get('companyDetails/create', ['as'=> 'companyDetails.create', 'uses' => 'Tradetailsconf\CompanyDetailsController@create']);
Route::put('companyDetails/{companyDetails}', ['as'=> 'companyDetails.update', 'uses' => 'Tradetailsconf\CompanyDetailsController@update']);
Route::patch('companyDetails/{companyDetails}', ['as'=> 'companyDetails.update', 'uses' => 'Tradetailsconf\CompanyDetailsController@update']);
Route::get('companyDetails/{id}/delete', ['as' => 'companyDetails.delete', 'uses' => 'Tradetailsconf\CompanyDetailsController@getDelete']);
Route::get('companyDetails/{id}/confirm-delete', ['as' => 'companyDetails.confirm-delete', 'uses' => 'Tradetailsconf\CompanyDetailsController@getModalDelete']);
Route::get('companyDetails/{companyDetails}', ['as'=> 'companyDetails.show', 'uses' => 'Tradetailsconf\CompanyDetailsController@show']);
Route::get('companyDetails/{companyDetails}/edit', ['as'=> 'companyDetails.edit', 'uses' => 'Tradetailsconf\CompanyDetailsController@edit']);

});


Route::group(array('prefix' => 'admin/traDetailsConf/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.traDetailsConf.'), function () {

Route::get('companyDetails', ['as'=> 'companyDetails.index', 'uses' => 'Tradetailsconf\CompanyDetailsController@index']);
Route::post('companyDetails', ['as'=> 'companyDetails.store', 'uses' => 'Tradetailsconf\CompanyDetailsController@store']);
Route::get('companyDetails/create', ['as'=> 'companyDetails.create', 'uses' => 'Tradetailsconf\CompanyDetailsController@create']);
Route::put('companyDetails/{companyDetails}', ['as'=> 'companyDetails.update', 'uses' => 'Tradetailsconf\CompanyDetailsController@update']);
Route::patch('companyDetails/{companyDetails}', ['as'=> 'companyDetails.update', 'uses' => 'Tradetailsconf\CompanyDetailsController@update']);
Route::get('companyDetails/{id}/delete', ['as' => 'companyDetails.delete', 'uses' => 'Tradetailsconf\CompanyDetailsController@getDelete']);
Route::get('companyDetails/{id}/confirm-delete', ['as' => 'companyDetails.confirm-delete', 'uses' => 'Tradetailsconf\CompanyDetailsController@getModalDelete']);
Route::get('companyDetails/{companyDetails}', ['as'=> 'companyDetails.show', 'uses' => 'Tradetailsconf\CompanyDetailsController@show']);
Route::get('companyDetails/{companyDetails}/edit', ['as'=> 'companyDetails.edit', 'uses' => 'Tradetailsconf\CompanyDetailsController@edit']);

});


Route::group(array('prefix' => 'admin/nidcConfigTra/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.nidcConfigTra.'), function () {

Route::get('nidcConfigs', ['as'=> 'nidcConfigs.index', 'uses' => 'Nidc_Config_Tra\NidcConfigController@index']);
Route::post('nidcConfigs', ['as'=> 'nidcConfigs.store', 'uses' => 'Nidc_Config_Tra\NidcConfigController@store']);
Route::get('nidcConfigs/create', ['as'=> 'nidcConfigs.create', 'uses' => 'Nidc_Config_Tra\NidcConfigController@create']);
//Route::post('nidcConfigs/traapi', ['as'=> 'nidcConfigs.traapi', 'uses' => 'Nidc_Config_Tra\NidcConfigController@processTraReceipt']);
Route::put('nidcConfigs/{nidcConfigs}', ['as'=> 'nidcConfigs.update', 'uses' => 'Nidc_Config_Tra\NidcConfigController@update']);
Route::patch('nidcConfigs/{nidcConfigs}', ['as'=> 'nidcConfigs.update', 'uses' => 'Nidc_Config_Tra\NidcConfigController@update']);
Route::get('nidcConfigs/{id}/delete', ['as' => 'nidcConfigs.delete', 'uses' => 'Nidc_Config_Tra\NidcConfigController@getDelete']);
Route::get('nidcConfigs/{id}/confirm-delete', ['as' => 'nidcConfigs.confirm-delete', 'uses' => 'Nidc_Config_Tra\NidcConfigController@getModalDelete']);
Route::get('nidcConfigs/{nidcConfigs}', ['as'=> 'nidcConfigs.show', 'uses' => 'Nidc_Config_Tra\NidcConfigController@show']);
Route::get('nidcConfigs/{nidcConfigs}/edit', ['as'=> 'nidcConfigs.edit', 'uses' => 'Nidc_Config_Tra\NidcConfigController@edit']);

});


Route::group(array('prefix' => 'admin/reports/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.reports.'), function () {

Route::get('reports', ['as'=> 'reports.index', 'uses' => 'Reports\ReportsController@index']);
Route::post('reports', ['as'=> 'reports.store', 'uses' => 'Reports\ReportsController@store']);
Route::get('reports/create', ['as'=> 'reports.create', 'uses' => 'Reports\ReportsController@create']);
Route::put('reports/{reports}', ['as'=> 'reports.update', 'uses' => 'Reports\ReportsController@update']);
Route::patch('reports/{reports}', ['as'=> 'reports.update', 'uses' => 'Reports\ReportsController@update']);
Route::get('reports/{id}/delete', ['as' => 'reports.delete', 'uses' => 'Reports\ReportsController@getDelete']);
Route::get('reports/{id}/confirm-delete', ['as' => 'reports.confirm-delete', 'uses' => 'Reports\ReportsController@getModalDelete']);
Route::get('reports/{reports}', ['as'=> 'reports.show', 'uses' => 'Reports\ReportsController@show']);
Route::get('reports/{reports}/edit', ['as'=> 'reports.edit', 'uses' => 'Reports\ReportsController@edit']);

});


Route::group(array('prefix' => 'admin/productrevenue/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.productrevenue.'), function () {

Route::get('productRevenues', ['as'=> 'productRevenues.index', 'uses' => 'Productrevenue\ProductRevenueController@index']);
Route::post('productRevenues', ['as'=> 'productRevenues.store', 'uses' => 'Productrevenue\ProductRevenueController@store']);
Route::get('productRevenues/create', ['as'=> 'productRevenues.create', 'uses' => 'Productrevenue\ProductRevenueController@create']);
Route::put('productRevenues/{productRevenues}', ['as'=> 'productRevenues.update', 'uses' => 'Productrevenue\ProductRevenueController@update']);
Route::patch('productRevenues/{productRevenues}', ['as'=> 'productRevenues.update', 'uses' => 'Productrevenue\ProductRevenueController@update']);
Route::get('productRevenues/{id}/delete', ['as' => 'productRevenues.delete', 'uses' => 'Productrevenue\ProductRevenueController@getDelete']);
Route::get('productRevenues/{id}/confirm-delete', ['as' => 'productRevenues.confirm-delete', 'uses' => 'Productrevenue\ProductRevenueController@getModalDelete']);
Route::get('productRevenues/{productRevenues}', ['as'=> 'productRevenues.show', 'uses' => 'Productrevenue\ProductRevenueController@show']);
Route::get('productRevenues/{productRevenues}/edit', ['as'=> 'productRevenues.edit', 'uses' => 'Productrevenue\ProductRevenueController@edit']);

});


Route::group(array('prefix' => 'admin/clientProduct/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.clientProduct.'), function () {

Route::get('clientProducts', ['as'=> 'clientProducts.index', 'uses' => 'Client_Product\Client_productController@index']);
Route::post('clientProducts', ['as'=> 'clientProducts.store', 'uses' => 'Client_Product\Client_productController@store']);
Route::get('clientProducts/create', ['as'=> 'clientProducts.create', 'uses' => 'Client_Product\Client_productController@create']);
Route::put('clientProducts/{clientProducts}', ['as'=> 'clientProducts.update', 'uses' => 'Client_Product\Client_productController@update']);
Route::patch('clientProducts/{clientProducts}', ['as'=> 'clientProducts.update', 'uses' => 'Client_Product\Client_productController@update']);
Route::get('clientProducts/{id}/delete', ['as' => 'clientProducts.delete', 'uses' => 'Client_Product\Client_productController@getDelete']);
Route::get('clientProducts/{id}/confirm-delete', ['as' => 'clientProducts.confirm-delete', 'uses' => 'Client_Product\Client_productController@getModalDelete']);
Route::get('clientProducts/{clientProducts}', ['as'=> 'clientProducts.show', 'uses' => 'Client_Product\Client_productController@show']);
Route::get('clientProducts/{clientProducts}/edit', ['as'=> 'clientProducts.edit', 'uses' => 'Client_Product\Client_productController@edit']);

});


Route::group(array('prefix' => 'admin/clientProduct/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.clientProduct.'), function () {

Route::get('clientproducts', ['as'=> 'clientproducts.index', 'uses' => 'Client_Product\ClientproductController@index']);
Route::post('clientproducts', ['as'=> 'clientproducts.store', 'uses' => 'Client_Product\ClientproductController@store']);
Route::get('clientproducts/create', ['as'=> 'clientproducts.create', 'uses' => 'Client_Product\ClientproductController@create']);
Route::put('clientproducts/{clientproducts}', ['as'=> 'clientproducts.update', 'uses' => 'Client_Product\ClientproductController@update']);
Route::patch('clientproducts/{clientproducts}', ['as'=> 'clientproducts.update', 'uses' => 'Client_Product\ClientproductController@update']);
Route::get('clientproducts/{id}/delete', ['as' => 'clientproducts.delete', 'uses' => 'Client_Product\ClientproductController@getDelete']);
Route::get('clientproducts/{id}/confirm-delete', ['as' => 'clientproducts.confirm-delete', 'uses' => 'Client_Product\ClientproductController@getModalDelete']);
Route::get('clientproducts/{clientproducts}', ['as'=> 'clientproducts.show', 'uses' => 'Client_Product\ClientproductController@show']);
Route::get('clientproducts/{clientproducts}/edit', ['as'=> 'clientproducts.edit', 'uses' => 'Client_Product\ClientproductController@edit']);

});


Route::group(array('prefix' => 'admin/clientProduct/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.clientProduct.'), function () {

Route::get('clientproductreports', ['as'=> 'clientproductreports.index', 'uses' => 'Client_Product\ClientproductreportController@index']);
Route::post('clientproductreports', ['as'=> 'clientproductreports.store', 'uses' => 'Client_Product\ClientproductreportController@store']);
Route::get('clientproductreports/create', ['as'=> 'clientproductreports.create', 'uses' => 'Client_Product\ClientproductreportController@create']);
Route::put('clientproductreports/{clientproductreports}', ['as'=> 'clientproductreports.update', 'uses' => 'Client_Product\ClientproductreportController@update']);
Route::patch('clientproductreports/{clientproductreports}', ['as'=> 'clientproductreports.update', 'uses' => 'Client_Product\ClientproductreportController@update']);
Route::get('clientproductreports/{id}/delete', ['as' => 'clientproductreports.delete', 'uses' => 'Client_Product\ClientproductreportController@getDelete']);
Route::get('clientproductreports/{id}/confirm-delete', ['as' => 'clientproductreports.confirm-delete', 'uses' => 'Client_Product\ClientproductreportController@getModalDelete']);
Route::get('clientproductreports/{clientproductreports}', ['as'=> 'clientproductreports.show', 'uses' => 'Client_Product\ClientproductreportController@show']);
Route::get('clientproductreports/{clientproductreports}/edit', ['as'=> 'clientproductreports.edit', 'uses' => 'Client_Product\ClientproductreportController@edit']);

});


Route::group(array('prefix' => 'admin/clientProduct/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.clientProduct.'), function () {

Route::get('productclients', ['as'=> 'productclients.index', 'uses' => 'Client_Product\ProductclientController@index']);
Route::post('productclients', ['as'=> 'productclients.store', 'uses' => 'Client_Product\ProductclientController@store']);
Route::get('productclients/create', ['as'=> 'productclients.create', 'uses' => 'Client_Product\ProductclientController@create']);
Route::put('productclients/{productclients}', ['as'=> 'productclients.update', 'uses' => 'Client_Product\ProductclientController@update']);
Route::patch('productclients/{productclients}', ['as'=> 'productclients.update', 'uses' => 'Client_Product\ProductclientController@update']);
Route::get('productclients/{id}/delete', ['as' => 'productclients.delete', 'uses' => 'Client_Product\ProductclientController@getDelete']);
Route::get('productclients/{id}/confirm-delete', ['as' => 'productclients.confirm-delete', 'uses' => 'Client_Product\ProductclientController@getModalDelete']);
Route::get('productclients/{productclients}', ['as'=> 'productclients.show', 'uses' => 'Client_Product\ProductclientController@show']);
Route::get('productclients/{productclients}/edit', ['as'=> 'productclients.edit', 'uses' => 'Client_Product\ProductclientController@edit']);

});


Route::group(array('prefix' => 'admin/clientProducts/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.clientProducts.'), function () {

Route::get('productclients', ['as'=> 'productclients.index', 'uses' => 'Client_Products\ProductclientController@index']);
Route::post('productclients', ['as'=> 'productclients.store', 'uses' => 'Client_Products\ProductclientController@store']);
Route::get('productclients/create', ['as'=> 'productclients.create', 'uses' => 'Client_Products\ProductclientController@create']);
Route::put('productclients/{productclients}', ['as'=> 'productclients.update', 'uses' => 'Client_Products\ProductclientController@update']);
Route::patch('productclients/{productclients}', ['as'=> 'productclients.update', 'uses' => 'Client_Products\ProductclientController@update']);
Route::get('productclients/{id}/delete', ['as' => 'productclients.delete', 'uses' => 'Client_Products\ProductclientController@getDelete']);
Route::get('productclients/{id}/confirm-delete', ['as' => 'productclients.confirm-delete', 'uses' => 'Client_Products\ProductclientController@getModalDelete']);
Route::get('productclients/{productclients}', ['as'=> 'productclients.show', 'uses' => 'Client_Products\ProductclientController@show']);
Route::get('productclients/{productclients}/edit', ['as'=> 'productclients.edit', 'uses' => 'Client_Products\ProductclientController@edit']);

});


Route::group(array('prefix' => 'admin/productsServiceOrder/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.productsServiceOrder.'), function () {

Route::get('productsServiceOrders', ['as'=> 'productsServiceOrders.index', 'uses' => 'Products_Service_Order\Products_service_orderController@index']);
Route::post('productsServiceOrders', ['as'=> 'productsServiceOrders.store', 'uses' => 'Products_Service_Order\Products_service_orderController@store']);
Route::get('productsServiceOrders/create', ['as'=> 'productsServiceOrders.create', 'uses' => 'Products_Service_Order\Products_service_orderController@create']);
Route::put('productsServiceOrders/{productsServiceOrders}', ['as'=> 'productsServiceOrders.update', 'uses' => 'Products_Service_Order\Products_service_orderController@update']);
Route::patch('productsServiceOrders/{productsServiceOrders}', ['as'=> 'productsServiceOrders.update', 'uses' => 'Products_Service_Order\Products_service_orderController@update']);
Route::get('productsServiceOrders/{id}/delete', ['as' => 'productsServiceOrders.delete', 'uses' => 'Products_Service_Order\Products_service_orderController@getDelete']);
Route::get('productsServiceOrders/{id}/confirm-delete', ['as' => 'productsServiceOrders.confirm-delete', 'uses' => 'Products_Service_Order\Products_service_orderController@getModalDelete']);
Route::get('productsServiceOrders/{productsServiceOrders}', ['as'=> 'productsServiceOrders.show', 'uses' => 'Products_Service_Order\Products_service_orderController@show']);
Route::get('productsServiceOrders/{productsServiceOrders}/edit', ['as'=> 'productsServiceOrders.edit', 'uses' => 'Products_Service_Order\Products_service_orderController@edit']);

});


Route::group(array('prefix' => 'admin/productsServicePrder/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.productsServicePrder.'), function () {

Route::get('productsserviceorders', ['as'=> 'productsserviceorders.index', 'uses' => 'Productsserviceprder\ProductsserviceorderController@index']);
Route::post('productsserviceorders', ['as'=> 'productsserviceorders.store', 'uses' => 'Productsserviceprder\ProductsserviceorderController@store']);
Route::get('productsserviceorders/create', ['as'=> 'productsserviceorders.create', 'uses' => 'Productsserviceprder\ProductsserviceorderController@create']);
Route::put('productsserviceorders/{productsserviceorders}', ['as'=> 'productsserviceorders.update', 'uses' => 'Productsserviceprder\ProductsserviceorderController@update']);
Route::patch('productsserviceorders/{productsserviceorders}', ['as'=> 'productsserviceorders.update', 'uses' => 'Productsserviceprder\ProductsserviceorderController@update']);
Route::get('productsserviceorders/{id}/delete', ['as' => 'productsserviceorders.delete', 'uses' => 'Productsserviceprder\ProductsserviceorderController@getDelete']);
Route::get('productsserviceorders/{id}/confirm-delete', ['as' => 'productsserviceorders.confirm-delete', 'uses' => 'Productsserviceprder\ProductsserviceorderController@getModalDelete']);
Route::get('productsserviceorders/{productsserviceorders}', ['as'=> 'productsserviceorders.show', 'uses' => 'Productsserviceprder\ProductsserviceorderController@show']);
Route::get('productsserviceorders/{productsserviceorders}/edit', ['as'=> 'productsserviceorders.edit', 'uses' => 'Productsserviceprder\ProductsserviceorderController@edit']);

});


Route::group(array('prefix' => 'admin/productServiceOrderList/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.productServiceOrderList.'), function () {

Route::get('productServiceOrderLists', ['as'=> 'productServiceOrderLists.index', 'uses' => 'Productserviceorderlist\ProductServiceOrderListController@index']);
Route::post('productServiceOrderLists', ['as'=> 'productServiceOrderLists.store', 'uses' => 'Productserviceorderlist\ProductServiceOrderListController@store']);
Route::get('productServiceOrderLists/create', ['as'=> 'productServiceOrderLists.create', 'uses' => 'Productserviceorderlist\ProductServiceOrderListController@create']);
Route::put('productServiceOrderLists/{productServiceOrderLists}', ['as'=> 'productServiceOrderLists.update', 'uses' => 'Productserviceorderlist\ProductServiceOrderListController@update']);
Route::patch('productServiceOrderLists/{productServiceOrderLists}', ['as'=> 'productServiceOrderLists.update', 'uses' => 'Productserviceorderlist\ProductServiceOrderListController@update']);
Route::get('productServiceOrderLists/{id}/delete', ['as' => 'productServiceOrderLists.delete', 'uses' => 'Productserviceorderlist\ProductServiceOrderListController@getDelete']);
Route::get('productServiceOrderLists/{id}/confirm-delete', ['as' => 'productServiceOrderLists.confirm-delete', 'uses' => 'Productserviceorderlist\ProductServiceOrderListController@getModalDelete']);
Route::get('productServiceOrderLists/{productServiceOrderLists}', ['as'=> 'productServiceOrderLists.show', 'uses' => 'Productserviceorderlist\ProductServiceOrderListController@show']);
Route::get('productServiceOrderLists/{productServiceOrderLists}/edit', ['as'=> 'productServiceOrderLists.edit', 'uses' => 'Productserviceorderlist\ProductServiceOrderListController@edit']);

});


Route::group(array('prefix' => 'admin/agingAnalysisReport/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.agingAnalysisReport.'), function () {

Route::get('aginganalysisreports', ['as'=> 'aginganalysisreports.index', 'uses' => 'Aginganalysisreport\AginganalysisreportController@index']);
Route::post('aginganalysisreports', ['as'=> 'aginganalysisreports.store', 'uses' => 'Aginganalysisreport\AginganalysisreportController@store']);
Route::get('aginganalysisreports/create', ['as'=> 'aginganalysisreports.create', 'uses' => 'Aginganalysisreport\AginganalysisreportController@create']);
Route::put('aginganalysisreports/{aginganalysisreports}', ['as'=> 'aginganalysisreports.update', 'uses' => 'Aginganalysisreport\AginganalysisreportController@update']);
Route::patch('aginganalysisreports/{aginganalysisreports}', ['as'=> 'aginganalysisreports.update', 'uses' => 'Aginganalysisreport\AginganalysisreportController@update']);
Route::get('aginganalysisreports/{id}/delete', ['as' => 'aginganalysisreports.delete', 'uses' => 'Aginganalysisreport\AginganalysisreportController@getDelete']);
Route::get('aginganalysisreports/{id}/confirm-delete', ['as' => 'aginganalysisreports.confirm-delete', 'uses' => 'Aginganalysisreport\AginganalysisreportController@getModalDelete']);
Route::get('aginganalysisreports/{aginganalysisreports}', ['as'=> 'aginganalysisreports.show', 'uses' => 'Aginganalysisreport\AginganalysisreportController@show']);
Route::get('aginganalysisreports/{aginganalysisreports}/edit', ['as'=> 'aginganalysisreports.edit', 'uses' => 'Aginganalysisreport\AginganalysisreportController@edit']);

});


Route::group(array('prefix' => 'admin/agingAnalysisReport/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.agingAnalysisReport.'), function () {

Route::get('aginganalysisreports', ['as'=> 'aginganalysisreports.index', 'uses' => 'Aginganalysisreport\AginganalysisreportController@index']);
Route::post('aginganalysisreports', ['as'=> 'aginganalysisreports.store', 'uses' => 'Aginganalysisreport\AginganalysisreportController@store']);
Route::get('aginganalysisreports/create', ['as'=> 'aginganalysisreports.create', 'uses' => 'Aginganalysisreport\AginganalysisreportController@create']);
Route::put('aginganalysisreports/{aginganalysisreports}', ['as'=> 'aginganalysisreports.update', 'uses' => 'Aginganalysisreport\AginganalysisreportController@update']);
Route::patch('aginganalysisreports/{aginganalysisreports}', ['as'=> 'aginganalysisreports.update', 'uses' => 'Aginganalysisreport\AginganalysisreportController@update']);
Route::get('aginganalysisreports/{id}/delete', ['as' => 'aginganalysisreports.delete', 'uses' => 'Aginganalysisreport\AginganalysisreportController@getDelete']);
Route::get('aginganalysisreports/{id}/confirm-delete', ['as' => 'aginganalysisreports.confirm-delete', 'uses' => 'Aginganalysisreport\AginganalysisreportController@getModalDelete']);
Route::get('aginganalysisreports/{aginganalysisreports}', ['as'=> 'aginganalysisreports.show', 'uses' => 'Aginganalysisreport\AginganalysisreportController@show']);
Route::get('aginganalysisreports/{aginganalysisreports}/edit', ['as'=> 'aginganalysisreports.edit', 'uses' => 'Aginganalysisreport\AginganalysisreportController@edit']);

});


Route::group(array('prefix' => 'admin/revenuePerCustomerReport/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.revenuePerCustomerReport.'), function () {

Route::get('revenuePerCustomerReports', ['as'=> 'revenuePerCustomerReports.index', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@index']);
Route::post('revenuePerCustomerReports', ['as'=> 'revenuePerCustomerReports.store', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@store']);
Route::get('revenuePerCustomerReports/create', ['as'=> 'revenuePerCustomerReports.create', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@create']);
Route::put('revenuePerCustomerReports/{revenuePerCustomerReports}', ['as'=> 'revenuePerCustomerReports.update', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@update']);
Route::patch('revenuePerCustomerReports/{revenuePerCustomerReports}', ['as'=> 'revenuePerCustomerReports.update', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@update']);
Route::get('revenuePerCustomerReports/{id}/delete', ['as' => 'revenuePerCustomerReports.delete', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@getDelete']);
Route::get('revenuePerCustomerReports/{id}/confirm-delete', ['as' => 'revenuePerCustomerReports.confirm-delete', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@getModalDelete']);
Route::get('revenuePerCustomerReports/{revenuePerCustomerReports}', ['as'=> 'revenuePerCustomerReports.show', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@show']);
Route::get('revenuePerCustomerReports/{revenuePerCustomerReports}/edit', ['as'=> 'revenuePerCustomerReports.edit', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@edit']);

});


Route::group(array('prefix' => 'admin/invoiceDublication/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.invoiceDublication.'), function () {

Route::get('invoiceDublications', ['as'=> 'invoiceDublications.index', 'uses' => 'Invoicedublication\InvoiceDublicationController@index']);
Route::post('invoiceDublications', ['as'=> 'invoiceDublications.store', 'uses' => 'Invoicedublication\InvoiceDublicationController@store']);
Route::get('invoiceDublications/create', ['as'=> 'invoiceDublications.create', 'uses' => 'Invoicedublication\InvoiceDublicationController@create']);
Route::put('invoiceDublications/{invoiceDublications}', ['as'=> 'invoiceDublications.update', 'uses' => 'Invoicedublication\InvoiceDublicationController@update']);
Route::patch('invoiceDublications/{invoiceDublications}', ['as'=> 'invoiceDublications.update', 'uses' => 'Invoicedublication\InvoiceDublicationController@update']);
Route::get('invoiceDublications/{id}/delete', ['as' => 'invoiceDublications.delete', 'uses' => 'Invoicedublication\InvoiceDublicationController@getDelete']);
Route::get('invoiceDublications/{id}/confirm-delete', ['as' => 'invoiceDublications.confirm-delete', 'uses' => 'Invoicedublication\InvoiceDublicationController@getModalDelete']);
Route::get('invoiceDublications/{invoiceDublications}', ['as'=> 'invoiceDublications.show', 'uses' => 'Invoicedublication\InvoiceDublicationController@show']);
Route::get('invoiceDublications/{invoiceDublications}/edit', ['as'=> 'invoiceDublications.edit', 'uses' => 'Invoicedublication\InvoiceDublicationController@edit']);

});


Route::group(array('prefix' => 'admin/invoiceDublication/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.invoiceDublication.'), function () {

Route::get('invoiceDublicationCreates', ['as'=> 'invoiceDublicationCreates.index', 'uses' => 'Invoicedublication\InvoiceDublicationCreateController@index']);
Route::post('invoiceDublicationCreates', ['as'=> 'invoiceDublicationCreates.store', 'uses' => 'Invoicedublication\InvoiceDublicationCreateController@store']);
Route::get('invoiceDublicationCreates/create', ['as'=> 'invoiceDublicationCreates.create', 'uses' => 'Invoicedublication\InvoiceDublicationCreateController@create']);
Route::put('invoiceDublicationCreates/{invoiceDublicationCreates}', ['as'=> 'invoiceDublicationCreates.update', 'uses' => 'Invoicedublication\InvoiceDublicationCreateController@update']);
Route::patch('invoiceDublicationCreates/{invoiceDublicationCreates}', ['as'=> 'invoiceDublicationCreates.update', 'uses' => 'Invoicedublication\InvoiceDublicationCreateController@update']);
Route::get('invoiceDublicationCreates/{id}/delete', ['as' => 'invoiceDublicationCreates.delete', 'uses' => 'Invoicedublication\InvoiceDublicationCreateController@getDelete']);
Route::get('invoiceDublicationCreates/{id}/confirm-delete', ['as' => 'invoiceDublicationCreates.confirm-delete', 'uses' => 'Invoicedublication\InvoiceDublicationCreateController@getModalDelete']);
Route::get('invoiceDublicationCreates/{invoiceDublicationCreates}', ['as'=> 'invoiceDublicationCreates.show', 'uses' => 'Invoicedublication\InvoiceDublicationCreateController@show']);
Route::get('invoiceDublicationCreates/{invoiceDublicationCreates}/edit', ['as'=> 'invoiceDublicationCreates.edit', 'uses' => 'Invoicedublication\InvoiceDublicationCreateController@edit']);

});
