<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/customer/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.customer.'), function () {

Route::get('customers', ['as'=> 'customers.index', 'uses' => 'Customer\CustomerController@index']);
Route::post('customers', ['as'=> 'customers.store', 'uses' => 'Customer\CustomerController@store']);
Route::get('customers/create', ['as'=> 'customers.create', 'uses' => 'Customer\CustomerController@create']);
Route::put('customers/{customers}', ['as'=> 'customers.update', 'uses' => 'Customer\CustomerController@update']);
Route::patch('customers/{customers}', ['as'=> 'customers.update', 'uses' => 'Customer\CustomerController@update']);
Route::get('customers/{id}/delete', ['as' => 'customers.delete', 'uses' => 'Customer\CustomerController@getDelete']);
Route::get('customers/{id}/confirm-delete', ['as' => 'customers.confirm-delete', 'uses' => 'Customer\CustomerController@getModalDelete']);
Route::get('customers/{customers}', ['as'=> 'customers.show', 'uses' => 'Customer\CustomerController@show']);
Route::get('customers/{customers}/edit', ['as'=> 'customers.edit', 'uses' => 'Customer\CustomerController@edit']);

});


Route::group(array('prefix' => 'admin/cusromerType/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.cusromerType.'), function () {

Route::get('customertypes', ['as'=> 'customertypes.index', 'uses' => 'Cusromer_Type\CustomertypeController@index']);
Route::post('customertypes', ['as'=> 'customertypes.store', 'uses' => 'Cusromer_Type\CustomertypeController@store']);
Route::get('customertypes/create', ['as'=> 'customertypes.create', 'uses' => 'Cusromer_Type\CustomertypeController@create']);
Route::put('customertypes/{customertypes}', ['as'=> 'customertypes.update', 'uses' => 'Cusromer_Type\CustomertypeController@update']);
Route::patch('customertypes/{customertypes}', ['as'=> 'customertypes.update', 'uses' => 'Cusromer_Type\CustomertypeController@update']);
Route::get('customertypes/{id}/delete', ['as' => 'customertypes.delete', 'uses' => 'Cusromer_Type\CustomertypeController@getDelete']);
Route::get('customertypes/{id}/confirm-delete', ['as' => 'customertypes.confirm-delete', 'uses' => 'Cusromer_Type\CustomertypeController@getModalDelete']);
Route::get('customertypes/{customertypes}', ['as'=> 'customertypes.show', 'uses' => 'Cusromer_Type\CustomertypeController@show']);
Route::get('customertypes/{customertypes}/edit', ['as'=> 'customertypes.edit', 'uses' => 'Cusromer_Type\CustomertypeController@edit']);

});


Route::group(array('prefix' => 'admin/customer/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.customer.'), function () {

Route::get('customers', ['as'=> 'customers.index', 'uses' => 'Customer\CustomerController@index']);
Route::post('customers', ['as'=> 'customers.store', 'uses' => 'Customer\CustomerController@store']);
Route::get('customers/create', ['as'=> 'customers.create', 'uses' => 'Customer\CustomerController@create']);
Route::put('customers/{customers}', ['as'=> 'customers.update', 'uses' => 'Customer\CustomerController@update']);
Route::patch('customers/{customers}', ['as'=> 'customers.update', 'uses' => 'Customer\CustomerController@update']);
Route::get('customers/{id}/delete', ['as' => 'customers.delete', 'uses' => 'Customer\CustomerController@getDelete']);
Route::get('customers/{id}/confirm-delete', ['as' => 'customers.confirm-delete', 'uses' => 'Customer\CustomerController@getModalDelete']);
Route::get('customers/{customers}', ['as'=> 'customers.show', 'uses' => 'Customer\CustomerController@show']);
Route::get('customers/{customers}/edit', ['as'=> 'customers.edit', 'uses' => 'Customer\CustomerController@edit']);

});


Route::group(array('prefix' => 'admin/product/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.product.'), function () {

Route::get('products', ['as'=> 'products.index', 'uses' => 'Product\ProductController@index']);
Route::post('products', ['as'=> 'products.store', 'uses' => 'Product\ProductController@store']);
Route::get('products/create', ['as'=> 'products.create', 'uses' => 'Product\ProductController@create']);
Route::put('products/{products}', ['as'=> 'products.update', 'uses' => 'Product\ProductController@update']);
Route::patch('products/{products}', ['as'=> 'products.update', 'uses' => 'Product\ProductController@update']);
Route::get('products/{id}/delete', ['as' => 'products.delete', 'uses' => 'Product\ProductController@getDelete']);
Route::get('products/{id}/confirm-delete', ['as' => 'products.confirm-delete', 'uses' => 'Product\ProductController@getModalDelete']);
Route::get('products/{products}', ['as'=> 'products.show', 'uses' => 'Product\ProductController@show']);
Route::get('products/{products}/edit', ['as'=> 'products.edit', 'uses' => 'Product\ProductController@edit']);

});


Route::group(array('prefix' => 'admin/productType/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.productType.'), function () {

Route::get('productTypes', ['as'=> 'productTypes.index', 'uses' => 'Product Type\ProductTypeController@index']);
Route::post('productTypes', ['as'=> 'productTypes.store', 'uses' => 'Product Type\ProductTypeController@store']);
Route::get('productTypes/create', ['as'=> 'productTypes.create', 'uses' => 'Product Type\ProductTypeController@create']);
Route::put('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type\ProductTypeController@update']);
Route::patch('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type\ProductTypeController@update']);
Route::get('productTypes/{id}/delete', ['as' => 'productTypes.delete', 'uses' => 'Product Type\ProductTypeController@getDelete']);
Route::get('productTypes/{id}/confirm-delete', ['as' => 'productTypes.confirm-delete', 'uses' => 'Product Type\ProductTypeController@getModalDelete']);
Route::get('productTypes/{productTypes}', ['as'=> 'productTypes.show', 'uses' => 'Product Type\ProductTypeController@show']);
Route::get('productTypes/{productTypes}/edit', ['as'=> 'productTypes.edit', 'uses' => 'Product Type\ProductTypeController@edit']);

});


Route::group(array('prefix' => 'admin/productType/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.productType.'), function () {

Route::get('productTypes', ['as'=> 'productTypes.index', 'uses' => 'Product Type\Product TypeController@index']);
Route::post('productTypes', ['as'=> 'productTypes.store', 'uses' => 'Product Type\Product TypeController@store']);
Route::get('productTypes/create', ['as'=> 'productTypes.create', 'uses' => 'Product Type\Product TypeController@create']);
Route::put('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type\Product TypeController@update']);
Route::patch('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type\Product TypeController@update']);
Route::get('productTypes/{id}/delete', ['as' => 'productTypes.delete', 'uses' => 'Product Type\Product TypeController@getDelete']);
Route::get('productTypes/{id}/confirm-delete', ['as' => 'productTypes.confirm-delete', 'uses' => 'Product Type\Product TypeController@getModalDelete']);
Route::get('productTypes/{productTypes}', ['as'=> 'productTypes.show', 'uses' => 'Product Type\Product TypeController@show']);
Route::get('productTypes/{productTypes}/edit', ['as'=> 'productTypes.edit', 'uses' => 'Product Type\Product TypeController@edit']);

});


Route::group(array('prefix' => 'admin/productType/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.productType.'), function () {

Route::get('productTypes', ['as'=> 'productTypes.index', 'uses' => 'Product Type\Product TypeController@index']);
Route::post('productTypes', ['as'=> 'productTypes.store', 'uses' => 'Product Type\Product TypeController@store']);
Route::get('productTypes/create', ['as'=> 'productTypes.create', 'uses' => 'Product Type\Product TypeController@create']);
Route::put('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type\Product TypeController@update']);
Route::patch('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type\Product TypeController@update']);
Route::get('productTypes/{id}/delete', ['as' => 'productTypes.delete', 'uses' => 'Product Type\Product TypeController@getDelete']);
Route::get('productTypes/{id}/confirm-delete', ['as' => 'productTypes.confirm-delete', 'uses' => 'Product Type\Product TypeController@getModalDelete']);
Route::get('productTypes/{productTypes}', ['as'=> 'productTypes.show', 'uses' => 'Product Type\Product TypeController@show']);
Route::get('productTypes/{productTypes}/edit', ['as'=> 'productTypes.edit', 'uses' => 'Product Type\Product TypeController@edit']);

});


Route::group(array('prefix' => 'admin/productType/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.productType.'), function () {

Route::get('productTypes', ['as'=> 'productTypes.index', 'uses' => 'Product Type\Product TypeController@index']);
Route::post('productTypes', ['as'=> 'productTypes.store', 'uses' => 'Product Type\Product TypeController@store']);
Route::get('productTypes/create', ['as'=> 'productTypes.create', 'uses' => 'Product Type\Product TypeController@create']);
Route::put('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type\Product TypeController@update']);
Route::patch('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type\Product TypeController@update']);
Route::get('productTypes/{id}/delete', ['as' => 'productTypes.delete', 'uses' => 'Product Type\Product TypeController@getDelete']);
Route::get('productTypes/{id}/confirm-delete', ['as' => 'productTypes.confirm-delete', 'uses' => 'Product Type\Product TypeController@getModalDelete']);
Route::get('productTypes/{productTypes}', ['as'=> 'productTypes.show', 'uses' => 'Product Type\Product TypeController@show']);
Route::get('productTypes/{productTypes}/edit', ['as'=> 'productTypes.edit', 'uses' => 'Product Type\Product TypeController@edit']);

});


Route::group(array('prefix' => 'admin/productTypeName/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.productTypeName.'), function () {

Route::get('productTypes', ['as'=> 'productTypes.index', 'uses' => 'Product Type Name\Product TypesController@index']);
Route::post('productTypes', ['as'=> 'productTypes.store', 'uses' => 'Product Type Name\Product TypesController@store']);
Route::get('productTypes/create', ['as'=> 'productTypes.create', 'uses' => 'Product Type Name\Product TypesController@create']);
Route::put('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type Name\Product TypesController@update']);
Route::patch('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type Name\Product TypesController@update']);
Route::get('productTypes/{id}/delete', ['as' => 'productTypes.delete', 'uses' => 'Product Type Name\Product TypesController@getDelete']);
Route::get('productTypes/{id}/confirm-delete', ['as' => 'productTypes.confirm-delete', 'uses' => 'Product Type Name\Product TypesController@getModalDelete']);
Route::get('productTypes/{productTypes}', ['as'=> 'productTypes.show', 'uses' => 'Product Type Name\Product TypesController@show']);
Route::get('productTypes/{productTypes}/edit', ['as'=> 'productTypes.edit', 'uses' => 'Product Type Name\Product TypesController@edit']);

});


Route::group(array('prefix' => 'admin/productTypeName/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.productTypeName.'), function () {

Route::get('productTypes', ['as'=> 'productTypes.index', 'uses' => 'Product Type Name\Product TypesController@index']);
Route::post('productTypes', ['as'=> 'productTypes.store', 'uses' => 'Product Type Name\Product TypesController@store']);
Route::get('productTypes/create', ['as'=> 'productTypes.create', 'uses' => 'Product Type Name\Product TypesController@create']);
Route::put('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type Name\Product TypesController@update']);
Route::patch('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Product Type Name\Product TypesController@update']);
Route::get('productTypes/{id}/delete', ['as' => 'productTypes.delete', 'uses' => 'Product Type Name\Product TypesController@getDelete']);
Route::get('productTypes/{id}/confirm-delete', ['as' => 'productTypes.confirm-delete', 'uses' => 'Product Type Name\Product TypesController@getModalDelete']);
Route::get('productTypes/{productTypes}', ['as'=> 'productTypes.show', 'uses' => 'Product Type Name\Product TypesController@show']);
Route::get('productTypes/{productTypes}/edit', ['as'=> 'productTypes.edit', 'uses' => 'Product Type Name\Product TypesController@edit']);

});


Route::group(array('prefix' => 'admin/serviceOrder/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.serviceOrder.'), function () {

Route::get('serviceOrders', ['as'=> 'serviceOrders.index', 'uses' => 'Service Order\Service OrderController@index']);
Route::post('serviceOrders', ['as'=> 'serviceOrders.store', 'uses' => 'Service Order\Service OrderController@store']);
Route::get('serviceOrders/create', ['as'=> 'serviceOrders.create', 'uses' => 'Service Order\Service OrderController@create']);
Route::put('serviceOrders/{serviceOrders}', ['as'=> 'serviceOrders.update', 'uses' => 'Service Order\Service OrderController@update']);
Route::patch('serviceOrders/{serviceOrders}', ['as'=> 'serviceOrders.update', 'uses' => 'Service Order\Service OrderController@update']);
Route::get('serviceOrders/{id}/delete', ['as' => 'serviceOrders.delete', 'uses' => 'Service Order\Service OrderController@getDelete']);
Route::get('serviceOrders/{id}/confirm-delete', ['as' => 'serviceOrders.confirm-delete', 'uses' => 'Service Order\Service OrderController@getModalDelete']);
Route::get('serviceOrders/{serviceOrders}', ['as'=> 'serviceOrders.show', 'uses' => 'Service Order\Service OrderController@show']);
Route::get('serviceOrders/{serviceOrders}/edit', ['as'=> 'serviceOrders.edit', 'uses' => 'Service Order\Service OrderController@edit']);

});


Route::group(array('prefix' => 'admin/serviceOrders/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.serviceOrders.'), function () {

Route::get('serviceOrders', ['as'=> 'serviceOrders.index', 'uses' => 'Service Orders\ServiceOrdersController@index']);
Route::post('serviceOrders', ['as'=> 'serviceOrders.store', 'uses' => 'Service Orders\ServiceOrdersController@store']);
Route::get('serviceOrders/create', ['as'=> 'serviceOrders.create', 'uses' => 'Service Orders\ServiceOrdersController@create']);
Route::put('serviceOrders/{serviceOrders}', ['as'=> 'serviceOrders.update', 'uses' => 'Service Orders\ServiceOrdersController@update']);
Route::patch('serviceOrders/{serviceOrders}', ['as'=> 'serviceOrders.update', 'uses' => 'Service Orders\ServiceOrdersController@update']);
Route::get('serviceOrders/{id}/delete', ['as' => 'serviceOrders.delete', 'uses' => 'Service Orders\ServiceOrdersController@getDelete']);
Route::get('serviceOrders/{id}/confirm-delete', ['as' => 'serviceOrders.confirm-delete', 'uses' => 'Service Orders\ServiceOrdersController@getModalDelete']);
Route::get('serviceOrders/{serviceOrders}', ['as'=> 'serviceOrders.show', 'uses' => 'Service Orders\ServiceOrdersController@show']);
Route::get('serviceOrders/{serviceOrders}/edit', ['as'=> 'serviceOrders.edit', 'uses' => 'Service Orders\ServiceOrdersController@edit']);

});


Route::group(array('prefix' => 'admin/serviceOrders/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.serviceOrders.'), function () {

Route::get('serviceOrders', ['as'=> 'serviceOrders.index', 'uses' => 'Serviceorders\ServiceOrdersController@index']);
Route::post('serviceOrders', ['as'=> 'serviceOrders.store', 'uses' => 'Serviceorders\ServiceOrdersController@store']);
Route::get('serviceOrders/create', ['as'=> 'serviceOrders.create', 'uses' => 'Serviceorders\ServiceOrdersController@create']);
Route::put('serviceOrders/{serviceOrders}', ['as'=> 'serviceOrders.update', 'uses' => 'Serviceorders\ServiceOrdersController@update']);
Route::patch('serviceOrders/{serviceOrders}', ['as'=> 'serviceOrders.update', 'uses' => 'Serviceorders\ServiceOrdersController@update']);
Route::get('serviceOrders/{id}/delete', ['as' => 'serviceOrders.delete', 'uses' => 'Serviceorders\ServiceOrdersController@getDelete']);
Route::get('serviceOrders/{id}/confirm-delete', ['as' => 'serviceOrders.confirm-delete', 'uses' => 'Serviceorders\ServiceOrdersController@getModalDelete']);
Route::get('serviceOrders/{serviceOrders}', ['as'=> 'serviceOrders.show', 'uses' => 'Serviceorders\ServiceOrdersController@show']);
Route::get('serviceOrders/{serviceOrders}/edit', ['as'=> 'serviceOrders.edit', 'uses' => 'Serviceorders\ServiceOrdersController@edit']);

});


Route::group(array('prefix' => 'admin/productType/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.productType.'), function () {

Route::get('productTypes', ['as'=> 'productTypes.index', 'uses' => 'Producttype\ProductTypeController@index']);
Route::post('productTypes', ['as'=> 'productTypes.store', 'uses' => 'Producttype\ProductTypeController@store']);
Route::get('productTypes/create', ['as'=> 'productTypes.create', 'uses' => 'Producttype\ProductTypeController@create']);
Route::put('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Producttype\ProductTypeController@update']);
Route::patch('productTypes/{productTypes}', ['as'=> 'productTypes.update', 'uses' => 'Producttype\ProductTypeController@update']);
Route::get('productTypes/{id}/delete', ['as' => 'productTypes.delete', 'uses' => 'Producttype\ProductTypeController@getDelete']);
Route::get('productTypes/{id}/confirm-delete', ['as' => 'productTypes.confirm-delete', 'uses' => 'Producttype\ProductTypeController@getModalDelete']);
Route::get('productTypes/{productTypes}', ['as'=> 'productTypes.show', 'uses' => 'Producttype\ProductTypeController@show']);
Route::get('productTypes/{productTypes}/edit', ['as'=> 'productTypes.edit', 'uses' => 'Producttype\ProductTypeController@edit']);

});


Route::group(array('prefix' => 'admin/paymentMode/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.paymentMode.'), function () {

Route::get('paymentModes', ['as'=> 'paymentModes.index', 'uses' => 'Paymentmode\PaymentModeController@index']);
Route::post('paymentModes', ['as'=> 'paymentModes.store', 'uses' => 'Paymentmode\PaymentModeController@store']);
Route::get('paymentModes/create', ['as'=> 'paymentModes.create', 'uses' => 'Paymentmode\PaymentModeController@create']);
Route::put('paymentModes/{paymentModes}', ['as'=> 'paymentModes.update', 'uses' => 'Paymentmode\PaymentModeController@update']);
Route::patch('paymentModes/{paymentModes}', ['as'=> 'paymentModes.update', 'uses' => 'Paymentmode\PaymentModeController@update']);
Route::get('paymentModes/{id}/delete', ['as' => 'paymentModes.delete', 'uses' => 'Paymentmode\PaymentModeController@getDelete']);
Route::get('paymentModes/{id}/confirm-delete', ['as' => 'paymentModes.confirm-delete', 'uses' => 'Paymentmode\PaymentModeController@getModalDelete']);
Route::get('paymentModes/{paymentModes}', ['as'=> 'paymentModes.show', 'uses' => 'Paymentmode\PaymentModeController@show']);
Route::get('paymentModes/{paymentModes}/edit', ['as'=> 'paymentModes.edit', 'uses' => 'Paymentmode\PaymentModeController@edit']);

});


Route::group(array('prefix' => 'admin/unitofMeasure/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.unitofMeasure.'), function () {

Route::get('unitofMeasures', ['as'=> 'unitofMeasures.index', 'uses' => 'Unitofmeasure\UnitofMeasureController@index']);
Route::post('unitofMeasures', ['as'=> 'unitofMeasures.store', 'uses' => 'Unitofmeasure\UnitofMeasureController@store']);
Route::get('unitofMeasures/create', ['as'=> 'unitofMeasures.create', 'uses' => 'Unitofmeasure\UnitofMeasureController@create']);
Route::put('unitofMeasures/{unitofMeasures}', ['as'=> 'unitofMeasures.update', 'uses' => 'Unitofmeasure\UnitofMeasureController@update']);
Route::patch('unitofMeasures/{unitofMeasures}', ['as'=> 'unitofMeasures.update', 'uses' => 'Unitofmeasure\UnitofMeasureController@update']);
Route::get('unitofMeasures/{id}/delete', ['as' => 'unitofMeasures.delete', 'uses' => 'Unitofmeasure\UnitofMeasureController@getDelete']);
Route::get('unitofMeasures/{id}/confirm-delete', ['as' => 'unitofMeasures.confirm-delete', 'uses' => 'Unitofmeasure\UnitofMeasureController@getModalDelete']);
Route::get('unitofMeasures/{unitofMeasures}', ['as'=> 'unitofMeasures.show', 'uses' => 'Unitofmeasure\UnitofMeasureController@show']);
Route::get('unitofMeasures/{unitofMeasures}/edit', ['as'=> 'unitofMeasures.edit', 'uses' => 'Unitofmeasure\UnitofMeasureController@edit']);

});


Route::group(array('prefix' => 'admin/customerType/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.customerType.'), function () {

Route::get('customerTypes', ['as'=> 'customerTypes.index', 'uses' => 'Customertype\CustomerTypeController@index']);
Route::post('customerTypes', ['as'=> 'customerTypes.store', 'uses' => 'Customertype\CustomerTypeController@store']);
Route::get('customerTypes/create', ['as'=> 'customerTypes.create', 'uses' => 'Customertype\CustomerTypeController@create']);
Route::put('customerTypes/{customerTypes}', ['as'=> 'customerTypes.update', 'uses' => 'Customertype\CustomerTypeController@update']);
Route::patch('customerTypes/{customerTypes}', ['as'=> 'customerTypes.update', 'uses' => 'Customertype\CustomerTypeController@update']);
Route::get('customerTypes/{id}/delete', ['as' => 'customerTypes.delete', 'uses' => 'Customertype\CustomerTypeController@getDelete']);
Route::get('customerTypes/{id}/confirm-delete', ['as' => 'customerTypes.confirm-delete', 'uses' => 'Customertype\CustomerTypeController@getModalDelete']);
Route::get('customerTypes/{customerTypes}', ['as'=> 'customerTypes.show', 'uses' => 'Customertype\CustomerTypeController@show']);
Route::get('customerTypes/{customerTypes}/edit', ['as'=> 'customerTypes.edit', 'uses' => 'Customertype\CustomerTypeController@edit']);

});


Route::group(array('prefix' => 'admin/paymentMode/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.paymentMode.'), function () {

Route::get('paymentModes', ['as'=> 'paymentModes.index', 'uses' => 'Paymentmode\PaymentModeController@index']);
Route::post('paymentModes', ['as'=> 'paymentModes.store', 'uses' => 'Paymentmode\PaymentModeController@store']);
Route::get('paymentModes/create', ['as'=> 'paymentModes.create', 'uses' => 'Paymentmode\PaymentModeController@create']);
Route::put('paymentModes/{paymentModes}', ['as'=> 'paymentModes.update', 'uses' => 'Paymentmode\PaymentModeController@update']);
Route::patch('paymentModes/{paymentModes}', ['as'=> 'paymentModes.update', 'uses' => 'Paymentmode\PaymentModeController@update']);
Route::get('paymentModes/{id}/delete', ['as' => 'paymentModes.delete', 'uses' => 'Paymentmode\PaymentModeController@getDelete']);
Route::get('paymentModes/{id}/confirm-delete', ['as' => 'paymentModes.confirm-delete', 'uses' => 'Paymentmode\PaymentModeController@getModalDelete']);
Route::get('paymentModes/{paymentModes}', ['as'=> 'paymentModes.show', 'uses' => 'Paymentmode\PaymentModeController@show']);
Route::get('paymentModes/{paymentModes}/edit', ['as'=> 'paymentModes.edit', 'uses' => 'Paymentmode\PaymentModeController@edit']);

});


Route::group(array('prefix' => 'admin/servicestatus/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.servicestatus.'), function () {

Route::get('servicestatuses', ['as'=> 'servicestatuses.index', 'uses' => 'Servicestatus\ServicestatusController@index']);
Route::post('servicestatuses', ['as'=> 'servicestatuses.store', 'uses' => 'Servicestatus\ServicestatusController@store']);
Route::get('servicestatuses/create', ['as'=> 'servicestatuses.create', 'uses' => 'Servicestatus\ServicestatusController@create']);
Route::put('servicestatuses/{servicestatuses}', ['as'=> 'servicestatuses.update', 'uses' => 'Servicestatus\ServicestatusController@update']);
Route::patch('servicestatuses/{servicestatuses}', ['as'=> 'servicestatuses.update', 'uses' => 'Servicestatus\ServicestatusController@update']);
Route::get('servicestatuses/{id}/delete', ['as' => 'servicestatuses.delete', 'uses' => 'Servicestatus\ServicestatusController@getDelete']);
Route::get('servicestatuses/{id}/confirm-delete', ['as' => 'servicestatuses.confirm-delete', 'uses' => 'Servicestatus\ServicestatusController@getModalDelete']);
Route::get('servicestatuses/{servicestatuses}', ['as'=> 'servicestatuses.show', 'uses' => 'Servicestatus\ServicestatusController@show']);
Route::get('servicestatuses/{servicestatuses}/edit', ['as'=> 'servicestatuses.edit', 'uses' => 'Servicestatus\ServicestatusController@edit']);

});


Route::group(array('prefix' => 'admin/serviceBilling/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.serviceBilling.'), function () {

Route::get('serviceBillings', ['as'=> 'serviceBillings.index', 'uses' => 'Servicebilling\ServiceBillingController@index']);
Route::post('serviceBillings', ['as'=> 'serviceBillings.store', 'uses' => 'Servicebilling\ServiceBillingController@store']);
Route::get('serviceBillings/create', ['as'=> 'serviceBillings.create', 'uses' => 'Servicebilling\ServiceBillingController@create']);
Route::put('serviceBillings/{serviceBillings}', ['as'=> 'serviceBillings.update', 'uses' => 'Servicebilling\ServiceBillingController@update']);
Route::patch('serviceBillings/{serviceBillings}', ['as'=> 'serviceBillings.update', 'uses' => 'Servicebilling\ServiceBillingController@update']);
Route::get('serviceBillings/{id}/delete', ['as' => 'serviceBillings.delete', 'uses' => 'Servicebilling\ServiceBillingController@getDelete']);
Route::get('serviceBillings/{id}/confirm-delete', ['as' => 'serviceBillings.confirm-delete', 'uses' => 'Servicebilling\ServiceBillingController@getModalDelete']);
Route::get('serviceBillings/{serviceBillings}', ['as'=> 'serviceBillings.show', 'uses' => 'Servicebilling\ServiceBillingController@show']);
Route::get('serviceBillings/{serviceBillings}/edit', ['as'=> 'serviceBillings.edit', 'uses' => 'Servicebilling\ServiceBillingController@edit']);

});


Route::group(array('prefix' => 'admin/serviceInvoice/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.serviceInvoice.'), function () {

Route::get('serviceInvoices', ['as'=> 'serviceInvoices.index', 'uses' => 'Serviceinvoice\ServiceInvoiceController@index']);
Route::post('serviceInvoices', ['as'=> 'serviceInvoices.store', 'uses' => 'Serviceinvoice\ServiceInvoiceController@store']);
Route::get('serviceInvoices/create', ['as'=> 'serviceInvoices.create', 'uses' => 'Serviceinvoice\ServiceInvoiceController@create']);
Route::put('serviceInvoices/{serviceInvoices}', ['as'=> 'serviceInvoices.update', 'uses' => 'Serviceinvoice\ServiceInvoiceController@update']);
Route::patch('serviceInvoices/{serviceInvoices}', ['as'=> 'serviceInvoices.update', 'uses' => 'Serviceinvoice\ServiceInvoiceController@update']);
Route::get('serviceInvoices/{id}/delete', ['as' => 'serviceInvoices.delete', 'uses' => 'Serviceinvoice\ServiceInvoiceController@getDelete']);
Route::get('serviceInvoices/{id}/confirm-delete', ['as' => 'serviceInvoices.confirm-delete', 'uses' => 'Serviceinvoice\ServiceInvoiceController@getModalDelete']);
Route::get('serviceInvoices/{serviceInvoices}', ['as'=> 'serviceInvoices.show', 'uses' => 'Serviceinvoice\ServiceInvoiceController@show']);
Route::get('serviceInvoices/{serviceInvoices}/edit', ['as'=> 'serviceInvoices.edit', 'uses' => 'Serviceinvoice\ServiceInvoiceController@edit']);

});


Route::group(array('prefix' => 'admin/paymentType/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.paymentType.'), function () {

Route::get('paymentTypes', ['as'=> 'paymentTypes.index', 'uses' => 'Paymenttype\PaymentTypeController@index']);
Route::post('paymentTypes', ['as'=> 'paymentTypes.store', 'uses' => 'Paymenttype\PaymentTypeController@store']);
Route::get('paymentTypes/create', ['as'=> 'paymentTypes.create', 'uses' => 'Paymenttype\PaymentTypeController@create']);
Route::put('paymentTypes/{paymentTypes}', ['as'=> 'paymentTypes.update', 'uses' => 'Paymenttype\PaymentTypeController@update']);
Route::patch('paymentTypes/{paymentTypes}', ['as'=> 'paymentTypes.update', 'uses' => 'Paymenttype\PaymentTypeController@update']);
Route::get('paymentTypes/{id}/delete', ['as' => 'paymentTypes.delete', 'uses' => 'Paymenttype\PaymentTypeController@getDelete']);
Route::get('paymentTypes/{id}/confirm-delete', ['as' => 'paymentTypes.confirm-delete', 'uses' => 'Paymenttype\PaymentTypeController@getModalDelete']);
Route::get('paymentTypes/{paymentTypes}', ['as'=> 'paymentTypes.show', 'uses' => 'Paymenttype\PaymentTypeController@show']);
Route::get('paymentTypes/{paymentTypes}/edit', ['as'=> 'paymentTypes.edit', 'uses' => 'Paymenttype\PaymentTypeController@edit']);

});


Route::group(array('prefix' => 'admin/paymentAndDue/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.paymentAndDue.'), function () {

Route::get('paymentAndDues', ['as'=> 'paymentAndDues.index', 'uses' => 'Paymentanddue\PaymentAndDueController@index']);
Route::post('paymentAndDues', ['as'=> 'paymentAndDues.store', 'uses' => 'Paymentanddue\PaymentAndDueController@store']);
Route::get('paymentAndDues/create', ['as'=> 'paymentAndDues.create', 'uses' => 'Paymentanddue\PaymentAndDueController@create']);
Route::put('paymentAndDues/{paymentAndDues}', ['as'=> 'paymentAndDues.update', 'uses' => 'Paymentanddue\PaymentAndDueController@update']);
Route::patch('paymentAndDues/{paymentAndDues}', ['as'=> 'paymentAndDues.update', 'uses' => 'Paymentanddue\PaymentAndDueController@update']);
Route::get('paymentAndDues/{id}/delete', ['as' => 'paymentAndDues.delete', 'uses' => 'Paymentanddue\PaymentAndDueController@getDelete']);
Route::get('paymentAndDues/{id}/confirm-delete', ['as' => 'paymentAndDues.confirm-delete', 'uses' => 'Paymentanddue\PaymentAndDueController@getModalDelete']);
Route::get('paymentAndDues/{paymentAndDues}', ['as'=> 'paymentAndDues.show', 'uses' => 'Paymentanddue\PaymentAndDueController@show']);
Route::get('paymentAndDues/{paymentAndDues}/edit', ['as'=> 'paymentAndDues.edit', 'uses' => 'Paymentanddue\PaymentAndDueController@edit']);

});


Route::group(array('prefix' => 'admin/invoicwePayment/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.invoicwePayment.'), function () {

Route::get('invoicwePayments', ['as'=> 'invoicwePayments.index', 'uses' => 'Invoicwepayment\InvoicwePaymentController@index']);
Route::post('invoicwePayments', ['as'=> 'invoicwePayments.store', 'uses' => 'Invoicwepayment\InvoicwePaymentController@store']);
Route::get('invoicwePayments/create', ['as'=> 'invoicwePayments.create', 'uses' => 'Invoicwepayment\InvoicwePaymentController@create']);
Route::put('invoicwePayments/{invoicwePayments}', ['as'=> 'invoicwePayments.update', 'uses' => 'Invoicwepayment\InvoicwePaymentController@update']);
Route::patch('invoicwePayments/{invoicwePayments}', ['as'=> 'invoicwePayments.update', 'uses' => 'Invoicwepayment\InvoicwePaymentController@update']);
Route::get('invoicwePayments/{id}/delete', ['as' => 'invoicwePayments.delete', 'uses' => 'Invoicwepayment\InvoicwePaymentController@getDelete']);
Route::get('invoicwePayments/{id}/confirm-delete', ['as' => 'invoicwePayments.confirm-delete', 'uses' => 'Invoicwepayment\InvoicwePaymentController@getModalDelete']);
Route::get('invoicwePayments/{invoicwePayments}', ['as'=> 'invoicwePayments.show', 'uses' => 'Invoicwepayment\InvoicwePaymentController@show']);
Route::get('invoicwePayments/{invoicwePayments}/edit', ['as'=> 'invoicwePayments.edit', 'uses' => 'Invoicwepayment\InvoicwePaymentController@edit']);

});


Route::group(array('prefix' => 'admin/serviceOrderType/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.serviceOrderType.'), function () {

Route::get('serviceOrderTypes', ['as'=> 'serviceOrderTypes.index', 'uses' => 'Serviceordertype\ServiceOrderTypeController@index']);
Route::post('serviceOrderTypes', ['as'=> 'serviceOrderTypes.store', 'uses' => 'Serviceordertype\ServiceOrderTypeController@store']);
Route::get('serviceOrderTypes/create', ['as'=> 'serviceOrderTypes.create', 'uses' => 'Serviceordertype\ServiceOrderTypeController@create']);
Route::put('serviceOrderTypes/{serviceOrderTypes}', ['as'=> 'serviceOrderTypes.update', 'uses' => 'Serviceordertype\ServiceOrderTypeController@update']);
Route::patch('serviceOrderTypes/{serviceOrderTypes}', ['as'=> 'serviceOrderTypes.update', 'uses' => 'Serviceordertype\ServiceOrderTypeController@update']);
Route::get('serviceOrderTypes/{id}/delete', ['as' => 'serviceOrderTypes.delete', 'uses' => 'Serviceordertype\ServiceOrderTypeController@getDelete']);
Route::get('serviceOrderTypes/{id}/confirm-delete', ['as' => 'serviceOrderTypes.confirm-delete', 'uses' => 'Serviceordertype\ServiceOrderTypeController@getModalDelete']);
Route::get('serviceOrderTypes/{serviceOrderTypes}', ['as'=> 'serviceOrderTypes.show', 'uses' => 'Serviceordertype\ServiceOrderTypeController@show']);
Route::get('serviceOrderTypes/{serviceOrderTypes}/edit', ['as'=> 'serviceOrderTypes.edit', 'uses' => 'Serviceordertype\ServiceOrderTypeController@edit']);

});


Route::group(array('prefix' => 'admin/comment/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.comment.'), function () {

Route::get('comments', ['as'=> 'comments.index', 'uses' => 'Comment\CommentController@index']);
Route::post('comments', ['as'=> 'comments.store', 'uses' => 'Comment\CommentController@store']);
Route::get('comments/create', ['as'=> 'comments.create', 'uses' => 'Comment\CommentController@create']);
Route::put('comments/{comments}', ['as'=> 'comments.update', 'uses' => 'Comment\CommentController@update']);
Route::patch('comments/{comments}', ['as'=> 'comments.update', 'uses' => 'Comment\CommentController@update']);
Route::get('comments/{id}/delete', ['as' => 'comments.delete', 'uses' => 'Comment\CommentController@getDelete']);
Route::get('comments/{id}/confirm-delete', ['as' => 'comments.confirm-delete', 'uses' => 'Comment\CommentController@getModalDelete']);
Route::get('comments/{comments}', ['as'=> 'comments.show', 'uses' => 'Comment\CommentController@show']);
Route::get('comments/{comments}/edit', ['as'=> 'comments.edit', 'uses' => 'Comment\CommentController@edit']);

});


Route::group(array('prefix' => 'admin/creditNote/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.creditNote.'), function () {

Route::get('creditNotes', ['as'=> 'creditNotes.index', 'uses' => 'Creditnote\CreditNoteController@index']);
Route::post('creditNotes', ['as'=> 'creditNotes.store', 'uses' => 'Creditnote\CreditNoteController@store']);
Route::get('creditNotes/create', ['as'=> 'creditNotes.create', 'uses' => 'Creditnote\CreditNoteController@create']);
Route::put('creditNotes/{creditNotes}', ['as'=> 'creditNotes.update', 'uses' => 'Creditnote\CreditNoteController@update']);
Route::patch('creditNotes/{creditNotes}', ['as'=> 'creditNotes.update', 'uses' => 'Creditnote\CreditNoteController@update']);
Route::get('creditNotes/{id}/delete', ['as' => 'creditNotes.delete', 'uses' => 'Creditnote\CreditNoteController@getDelete']);
Route::get('creditNotes/{id}/confirm-delete', ['as' => 'creditNotes.confirm-delete', 'uses' => 'Creditnote\CreditNoteController@getModalDelete']);
Route::get('creditNotes/{creditNotes}', ['as'=> 'creditNotes.show', 'uses' => 'Creditnote\CreditNoteController@show']);
Route::get('creditNotes/{creditNotes}/edit', ['as'=> 'creditNotes.edit', 'uses' => 'Creditnote\CreditNoteController@edit']);

});


Route::group(array('prefix' => 'admin/agingAnalysisReport/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.agingAnalysisReport.'), function () {

Route::get('agingAnalysisReports', ['as'=> 'agingAnalysisReports.index', 'uses' => 'Aginganalysisreport\AgingAnalysisReportController@index']);
Route::post('agingAnalysisReports', ['as'=> 'agingAnalysisReports.store', 'uses' => 'Aginganalysisreport\AgingAnalysisReportController@store']);
Route::get('agingAnalysisReports/create', ['as'=> 'agingAnalysisReports.create', 'uses' => 'Aginganalysisreport\AgingAnalysisReportController@create']);
Route::put('agingAnalysisReports/{agingAnalysisReports}', ['as'=> 'agingAnalysisReports.update', 'uses' => 'Aginganalysisreport\AgingAnalysisReportController@update']);
Route::patch('agingAnalysisReports/{agingAnalysisReports}', ['as'=> 'agingAnalysisReports.update', 'uses' => 'Aginganalysisreport\AgingAnalysisReportController@update']);
Route::get('agingAnalysisReports/{id}/delete', ['as' => 'agingAnalysisReports.delete', 'uses' => 'Aginganalysisreport\AgingAnalysisReportController@getDelete']);
Route::get('agingAnalysisReports/{id}/confirm-delete', ['as' => 'agingAnalysisReports.confirm-delete', 'uses' => 'Aginganalysisreport\AgingAnalysisReportController@getModalDelete']);
Route::get('agingAnalysisReports/{agingAnalysisReports}', ['as'=> 'agingAnalysisReports.show', 'uses' => 'Aginganalysisreport\AgingAnalysisReportController@show']);
Route::get('agingAnalysisReports/{agingAnalysisReports}/edit', ['as'=> 'agingAnalysisReports.edit', 'uses' => 'Aginganalysisreport\AgingAnalysisReportController@edit']);

});


Route::group(array('prefix' => 'admin/revenuePerCustomerReport/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.revenuePerCustomerReport.'), function () {

Route::get('revenuePerCustomerReports', ['as'=> 'revenuePerCustomerReports.index', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@index']);
Route::post('revenuePerCustomerReports', ['as'=> 'revenuePerCustomerReports.store', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@store']);
Route::get('revenuePerCustomerReports/create', ['as'=> 'revenuePerCustomerReports.create', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@create']);
Route::put('revenuePerCustomerReports/{revenuePerCustomerReports}', ['as'=> 'revenuePerCustomerReports.update', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@update']);
Route::patch('revenuePerCustomerReports/{revenuePerCustomerReports}', ['as'=> 'revenuePerCustomerReports.update', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@update']);
Route::get('revenuePerCustomerReports/{id}/delete', ['as' => 'revenuePerCustomerReports.delete', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@getDelete']);
Route::get('revenuePerCustomerReports/{id}/confirm-delete', ['as' => 'revenuePerCustomerReports.confirm-delete', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@getModalDelete']);
Route::get('revenuePerCustomerReports/{revenuePerCustomerReports}', ['as'=> 'revenuePerCustomerReports.show', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@show']);
Route::get('revenuePerCustomerReports/{revenuePerCustomerReports}/edit', ['as'=> 'revenuePerCustomerReports.edit', 'uses' => 'Revenuepercustomerreport\RevenuePerCustomerReportController@edit']);

});


Route::group(array('prefix' => 'admin/traDetailsConf/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.traDetailsConf.'), function () {

Route::get('traDetailsConfs', ['as'=> 'traDetailsConfs.index', 'uses' => 'Tra_Details_Conf\Tra_details_confController@index']);
Route::post('traDetailsConfs', ['as'=> 'traDetailsConfs.store', 'uses' => 'Tra_Details_Conf\Tra_details_confController@store']);
Route::get('traDetailsConfs/create', ['as'=> 'traDetailsConfs.create', 'uses' => 'Tra_Details_Conf\Tra_details_confController@create']);
Route::put('traDetailsConfs/{traDetailsConfs}', ['as'=> 'traDetailsConfs.update', 'uses' => 'Tra_Details_Conf\Tra_details_confController@update']);
Route::patch('traDetailsConfs/{traDetailsConfs}', ['as'=> 'traDetailsConfs.update', 'uses' => 'Tra_Details_Conf\Tra_details_confController@update']);
Route::get('traDetailsConfs/{id}/delete', ['as' => 'traDetailsConfs.delete', 'uses' => 'Tra_Details_Conf\Tra_details_confController@getDelete']);
Route::get('traDetailsConfs/{id}/confirm-delete', ['as' => 'traDetailsConfs.confirm-delete', 'uses' => 'Tra_Details_Conf\Tra_details_confController@getModalDelete']);
Route::get('traDetailsConfs/{traDetailsConfs}', ['as'=> 'traDetailsConfs.show', 'uses' => 'Tra_Details_Conf\Tra_details_confController@show']);
Route::get('traDetailsConfs/{traDetailsConfs}/edit', ['as'=> 'traDetailsConfs.edit', 'uses' => 'Tra_Details_Conf\Tra_details_confController@edit']);

});


Route::group(array('prefix' => 'admin/traDetailsConf/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.traDetailsConf.'), function () {

Route::get('traDetailsConfs', ['as'=> 'traDetailsConfs.index', 'uses' => 'Tra_Details_Conf\Tra_details_confController@index']);
Route::post('traDetailsConfs', ['as'=> 'traDetailsConfs.store', 'uses' => 'Tra_Details_Conf\Tra_details_confController@store']);
Route::get('traDetailsConfs/create', ['as'=> 'traDetailsConfs.create', 'uses' => 'Tra_Details_Conf\Tra_details_confController@create']);
Route::put('traDetailsConfs/{traDetailsConfs}', ['as'=> 'traDetailsConfs.update', 'uses' => 'Tra_Details_Conf\Tra_details_confController@update']);
Route::patch('traDetailsConfs/{traDetailsConfs}', ['as'=> 'traDetailsConfs.update', 'uses' => 'Tra_Details_Conf\Tra_details_confController@update']);
Route::get('traDetailsConfs/{id}/delete', ['as' => 'traDetailsConfs.delete', 'uses' => 'Tra_Details_Conf\Tra_details_confController@getDelete']);
Route::get('traDetailsConfs/{id}/confirm-delete', ['as' => 'traDetailsConfs.confirm-delete', 'uses' => 'Tra_Details_Conf\Tra_details_confController@getModalDelete']);
Route::get('traDetailsConfs/{traDetailsConfs}', ['as'=> 'traDetailsConfs.show', 'uses' => 'Tra_Details_Conf\Tra_details_confController@show']);
Route::get('traDetailsConfs/{traDetailsConfs}/edit', ['as'=> 'traDetailsConfs.edit', 'uses' => 'Tra_Details_Conf\Tra_details_confController@edit']);

});


Route::group(array('prefix' => 'admin/traDetailsConf/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.traDetailsConf.'), function () {

Route::get('tradetailsconfs', ['as'=> 'tradetailsconfs.index', 'uses' => 'Tra_Details_Conf\TradetailsconfController@index']);
Route::post('tradetailsconfs', ['as'=> 'tradetailsconfs.store', 'uses' => 'Tra_Details_Conf\TradetailsconfController@store']);
Route::get('tradetailsconfs/create', ['as'=> 'tradetailsconfs.create', 'uses' => 'Tra_Details_Conf\TradetailsconfController@create']);
Route::put('tradetailsconfs/{tradetailsconfs}', ['as'=> 'tradetailsconfs.update', 'uses' => 'Tra_Details_Conf\TradetailsconfController@update']);
Route::patch('tradetailsconfs/{tradetailsconfs}', ['as'=> 'tradetailsconfs.update', 'uses' => 'Tra_Details_Conf\TradetailsconfController@update']);
Route::get('tradetailsconfs/{id}/delete', ['as' => 'tradetailsconfs.delete', 'uses' => 'Tra_Details_Conf\TradetailsconfController@getDelete']);
Route::get('tradetailsconfs/{id}/confirm-delete', ['as' => 'tradetailsconfs.confirm-delete', 'uses' => 'Tra_Details_Conf\TradetailsconfController@getModalDelete']);
Route::get('tradetailsconfs/{tradetailsconfs}', ['as'=> 'tradetailsconfs.show', 'uses' => 'Tra_Details_Conf\TradetailsconfController@show']);
Route::get('tradetailsconfs/{tradetailsconfs}/edit', ['as'=> 'tradetailsconfs.edit', 'uses' => 'Tra_Details_Conf\TradetailsconfController@edit']);

});


Route::group(array('prefix' => 'admin/traDetailsConf/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.traDetailsConf.'), function () {

Route::get('tradetailsconfs', ['as'=> 'tradetailsconfs.index', 'uses' => 'Tra_Details_Conf\TradetailsconfController@index']);
Route::post('tradetailsconfs', ['as'=> 'tradetailsconfs.store', 'uses' => 'Tra_Details_Conf\TradetailsconfController@store']);
Route::get('tradetailsconfs/create', ['as'=> 'tradetailsconfs.create', 'uses' => 'Tra_Details_Conf\TradetailsconfController@create']);
Route::put('tradetailsconfs/{tradetailsconfs}', ['as'=> 'tradetailsconfs.update', 'uses' => 'Tra_Details_Conf\TradetailsconfController@update']);
Route::patch('tradetailsconfs/{tradetailsconfs}', ['as'=> 'tradetailsconfs.update', 'uses' => 'Tra_Details_Conf\TradetailsconfController@update']);
Route::get('tradetailsconfs/{id}/delete', ['as' => 'tradetailsconfs.delete', 'uses' => 'Tra_Details_Conf\TradetailsconfController@getDelete']);
Route::get('tradetailsconfs/{id}/confirm-delete', ['as' => 'tradetailsconfs.confirm-delete', 'uses' => 'Tra_Details_Conf\TradetailsconfController@getModalDelete']);
Route::get('tradetailsconfs/{tradetailsconfs}', ['as'=> 'tradetailsconfs.show', 'uses' => 'Tra_Details_Conf\TradetailsconfController@show']);
Route::get('tradetailsconfs/{tradetailsconfs}/edit', ['as'=> 'tradetailsconfs.edit', 'uses' => 'Tra_Details_Conf\TradetailsconfController@edit']);

});


Route::group(array('prefix' => 'admin/traDetailsConf/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.traDetailsConf.'), function () {

Route::get('tradetailsconfs', ['as'=> 'tradetailsconfs.index', 'uses' => 'Tradetailsconf\TradetailsconfController@index']);
Route::post('tradetailsconfs', ['as'=> 'tradetailsconfs.store', 'uses' => 'Tradetailsconf\TradetailsconfController@store']);
Route::get('tradetailsconfs/create', ['as'=> 'tradetailsconfs.create', 'uses' => 'Tradetailsconf\TradetailsconfController@create']);
Route::put('tradetailsconfs/{tradetailsconfs}', ['as'=> 'tradetailsconfs.update', 'uses' => 'Tradetailsconf\TradetailsconfController@update']);
Route::patch('tradetailsconfs/{tradetailsconfs}', ['as'=> 'tradetailsconfs.update', 'uses' => 'Tradetailsconf\TradetailsconfController@update']);
Route::get('tradetailsconfs/{id}/delete', ['as' => 'tradetailsconfs.delete', 'uses' => 'Tradetailsconf\TradetailsconfController@getDelete']);
Route::get('tradetailsconfs/{id}/confirm-delete', ['as' => 'tradetailsconfs.confirm-delete', 'uses' => 'Tradetailsconf\TradetailsconfController@getModalDelete']);
Route::get('tradetailsconfs/{tradetailsconfs}', ['as'=> 'tradetailsconfs.show', 'uses' => 'Tradetailsconf\TradetailsconfController@show']);
Route::get('tradetailsconfs/{tradetailsconfs}/edit', ['as'=> 'tradetailsconfs.edit', 'uses' => 'Tradetailsconf\TradetailsconfController@edit']);

});


Route::group(array('prefix' => 'admin/traDetailsConf/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.traDetailsConf.'), function () {

Route::get('companyDetails', ['as'=> 'companyDetails.index', 'uses' => 'Tradetailsconf\CompanyDetailsController@index']);
Route::post('companyDetails', ['as'=> 'companyDetails.store', 'uses' => 'Tradetailsconf\CompanyDetailsController@store']);
Route::get('companyDetails/create', ['as'=> 'companyDetails.create', 'uses' => 'Tradetailsconf\CompanyDetailsController@create']);
Route::put('companyDetails/{companyDetails}', ['as'=> 'companyDetails.update', 'uses' => 'Tradetailsconf\CompanyDetailsController@update']);
Route::patch('companyDetails/{companyDetails}', ['as'=> 'companyDetails.update', 'uses' => 'Tradetailsconf\CompanyDetailsController@update']);
Route::get('companyDetails/{id}/delete', ['as' => 'companyDetails.delete', 'uses' => 'Tradetailsconf\CompanyDetailsController@getDelete']);
Route::get('companyDetails/{id}/confirm-delete', ['as' => 'companyDetails.confirm-delete', 'uses' => 'Tradetailsconf\CompanyDetailsController@getModalDelete']);
Route::get('companyDetails/{companyDetails}', ['as'=> 'companyDetails.show', 'uses' => 'Tradetailsconf\CompanyDetailsController@show']);
Route::get('companyDetails/{companyDetails}/edit', ['as'=> 'companyDetails.edit', 'uses' => 'Tradetailsconf\CompanyDetailsController@edit']);

});


Route::group(array('prefix' => 'admin/traDetailsConf/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.traDetailsConf.'), function () {

Route::get('companyDetails', ['as'=> 'companyDetails.index', 'uses' => 'Tradetailsconf\CompanyDetailsController@index']);
Route::post('companyDetails', ['as'=> 'companyDetails.store', 'uses' => 'Tradetailsconf\CompanyDetailsController@store']);
Route::get('companyDetails/create', ['as'=> 'companyDetails.create', 'uses' => 'Tradetailsconf\CompanyDetailsController@create']);
Route::put('companyDetails/{companyDetails}', ['as'=> 'companyDetails.update', 'uses' => 'Tradetailsconf\CompanyDetailsController@update']);
Route::patch('companyDetails/{companyDetails}', ['as'=> 'companyDetails.update', 'uses' => 'Tradetailsconf\CompanyDetailsController@update']);
Route::get('companyDetails/{id}/delete', ['as' => 'companyDetails.delete', 'uses' => 'Tradetailsconf\CompanyDetailsController@getDelete']);
Route::get('companyDetails/{id}/confirm-delete', ['as' => 'companyDetails.confirm-delete', 'uses' => 'Tradetailsconf\CompanyDetailsController@getModalDelete']);
Route::get('companyDetails/{companyDetails}', ['as'=> 'companyDetails.show', 'uses' => 'Tradetailsconf\CompanyDetailsController@show']);
Route::get('companyDetails/{companyDetails}/edit', ['as'=> 'companyDetails.edit', 'uses' => 'Tradetailsconf\CompanyDetailsController@edit']);

});


Route::group(array('prefix' => 'admin/traDetailsConf/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.traDetailsConf.'), function () {

Route::get('companyDetails', ['as'=> 'companyDetails.index', 'uses' => 'Tradetailsconf\CompanyDetailsController@index']);
Route::post('companyDetails', ['as'=> 'companyDetails.store', 'uses' => 'Tradetailsconf\CompanyDetailsController@store']);
Route::get('companyDetails/create', ['as'=> 'companyDetails.create', 'uses' => 'Tradetailsconf\CompanyDetailsController@create']);
Route::put('companyDetails/{companyDetails}', ['as'=> 'companyDetails.update', 'uses' => 'Tradetailsconf\CompanyDetailsController@update']);
Route::patch('companyDetails/{companyDetails}', ['as'=> 'companyDetails.update', 'uses' => 'Tradetailsconf\CompanyDetailsController@update']);
Route::get('companyDetails/{id}/delete', ['as' => 'companyDetails.delete', 'uses' => 'Tradetailsconf\CompanyDetailsController@getDelete']);
Route::get('companyDetails/{id}/confirm-delete', ['as' => 'companyDetails.confirm-delete', 'uses' => 'Tradetailsconf\CompanyDetailsController@getModalDelete']);
Route::get('companyDetails/{companyDetails}', ['as'=> 'companyDetails.show', 'uses' => 'Tradetailsconf\CompanyDetailsController@show']);
Route::get('companyDetails/{companyDetails}/edit', ['as'=> 'companyDetails.edit', 'uses' => 'Tradetailsconf\CompanyDetailsController@edit']);

});


Route::group(array('prefix' => 'admin/nidcConfigTra/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.nidcConfigTra.'), function () {

Route::get('nidcConfigs', ['as'=> 'nidcConfigs.index', 'uses' => 'Nidc_Config_Tra\NidcConfigController@index']);
Route::post('nidcConfigs', ['as'=> 'nidcConfigs.store', 'uses' => 'Nidc_Config_Tra\NidcConfigController@store']);
Route::get('nidcConfigs/create', ['as'=> 'nidcConfigs.create', 'uses' => 'Nidc_Config_Tra\NidcConfigController@create']);
Route::post('nidcConfigs/traapi', ['as'=> 'nidcConfigs.traapi', 'uses' => 'Nidc_Config_Tra\NidcConfigController@processTraReceipt']);
Route::put('nidcConfigs/{nidcConfigs}', ['as'=> 'nidcConfigs.update', 'uses' => 'Nidc_Config_Tra\NidcConfigController@update']);
Route::patch('nidcConfigs/{nidcConfigs}', ['as'=> 'nidcConfigs.update', 'uses' => 'Nidc_Config_Tra\NidcConfigController@update']);
Route::get('nidcConfigs/{id}/delete', ['as' => 'nidcConfigs.delete', 'uses' => 'Nidc_Config_Tra\NidcConfigController@getDelete']);
Route::get('nidcConfigs/{id}/confirm-delete', ['as' => 'nidcConfigs.confirm-delete', 'uses' => 'Nidc_Config_Tra\NidcConfigController@getModalDelete']);
Route::get('nidcConfigs/{nidcConfigs}', ['as'=> 'nidcConfigs.show', 'uses' => 'Nidc_Config_Tra\NidcConfigController@show']);
Route::get('nidcConfigs/{nidcConfigs}/edit', ['as'=> 'nidcConfigs.edit', 'uses' => 'Nidc_Config_Tra\NidcConfigController@edit']);

});
